---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  values:
    controller:
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-prod.star.pekware.club"
      replicaCount: 2
      service:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "ingress.pekware.club"
    tcp:
      "222": "gitea/gitea-ssh:222"
