kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- extraPortMappings:
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 222
    hostPort: 222
    protocol: TCP
- role: worker
networking:
  disableDefaultCNI: false
