apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/external-dns/
  - sealed.secret.do-token.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
