apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: do-token
  namespace: external-dns
spec:
  encryptedData:
    do-token: AgA4ncvHwnubKjwJbDlYUWvDNfGv8aqy86tqi1YxrErohAw1pF1Nz97uQQh8GpYx/BWeB73Ubrtk/Ol6OyBnJS1WB8e5PgVWd1A29f7DzQfkROwHXajWIPM2rb8MkUndr6uxkzliZqS/cbBuwu7jkoCzk/Hpr9sz+lsvFjIspUfcbESZUJgVSJmup4c+3GfEQ6IKhLhwo+JQcv2zbp9OnRYWsn6/5ZME5BXi/z//2omHK/WKCPyTFqhhMTD6K+o0Ix7kD8lnNWercT8o3l8bd8lCYzG1T24szrevhrkxFXX4DXuA9kX9ZXglcJEMa+YkqLQIk7tS9oZFd4ggbg0yFxNwjXITRtwL4gOZonrDD21majwv6Dt0QJpP065nogMZdJBmNyHjhAPlKX1Mg6vb9iTyuTGF5U/QO1OaODTJSS6iT84ZJI/8h4hFN98bmHR1KEYxVspv2NHuUXI7NsDTUv6vuKcvH0UYAS9SMeMNEXG35SON8Ztx+A+cVeVBdz6mcqpoaDGYIN25aKpOIdu9vWFlnyUwlnxNpdJkiYgC2V80QRFCCGOdibnFS8OLeL1lJoxuCGpt+lN7Dtx5uYebaYEi/c7enWCgvw+B7COvXicMrtgVwO3iRcaZOSsILKeqGek2ICXfZpzbhe9EYpTemmDXLh4vneHamDwed8VUqwCVl7a4SnuMypsIIaUjjgkK8MJTpgCSH+4vrp/PPiBm+2joCuhJywiTTixb/irPTo9x+BItlDfA/YRF5XUUPMvHqsXxbcB+Wf4c8/EFswpZoBUZR9yXoCrLgg==
  template:
    metadata:
      creationTimestamp: null
      name: do-token
      namespace: external-dns
