---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: bitnami-redis
spec:
  encryptedData:
    redis-password: AgAzve768/5J2uU523vN7GVRQf5DlXSZA2EwPP9/ikNmY+E0bA364QU0HTfRqL3oNnrpeAYgJvobR6WP2AMDVTcUGCOq38zGSOwjjiolpdp7lS/FvSz8zfMnLUQN5JFD1J+wz+QB73EJiyLeVzio9l6fcWB5hG9mixtHhy6Sd8jIhICBrxQk9xL/r5fh25ki/r1CaR8bbmGNKBXwppSgUs8vKi2wyYgQTt2oaPJml5jTVrvT+T2BNlsU+TaKXk4dOqt+dQz30nk4wAVY1Ma1mBmB8wY9f4EFDG2l6dWayf9uh043FV4kJXrxMpH4rd8fkWO9/82tcEQnq8ge2Oo7aPNuDTJJl0OZmgfdAF26di+dNMUr3k2LPjrLO/mVlEnOFSDLuJhihJzmZ4fGxovf8ZLl4IBDj8dkFM/OIDcf+oC59ml1e5yq21mEN4LyP4k1rdZCB6tPmA5Aciv5ecY9FrjuXaJYqSNjk9Ekuz+JXLynHaqWnaJnsT07WJWKdpXfyFvv3BGOSYkPJgT0U3kvaWwBu5bvg1jz0+lx9S0zrXMj11VXIgsjG6A5pTGM0xN8PhEp8KPxT7OkdEzZaj1CI3E3VT9zjyPMYo+XEwR6gvqf3tqzYU/bu3Wtj01mm9JUDySY9Weo2SRhdjIKtjzWRA5jv41IIgYWwHAqOPpWdxM87NOIkxiiy5S/nALHwLG1aQlaM3ME7e1B02TdjouV+VJXTh4TBqZ8KpJTr4DIxtXnRw==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: bitnami-redis
