apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/mnt/pool/volumes/production/gitea"
    server: data.pekware.xyz
    readOnly: false
  claimRef:
    name: gitea-pvc
    namespace: gitea
