apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  values:
    clusterDomain: gitea.pekware.club
    ingress:
      enabled: true
      hosts:
        - host: gitea.pekware.club
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: star.pekware.club
          hosts:
            - gitea.pekware.club
    persistence:
      enabled: true
      existingClaim: gitea
    gitea:
      admin:
        existingSecret: gitea-admin-secret
        email: king.phil@gmail.com
      config:
        database:
          DB_TYPE: mysql
          HOST: mysql:3306
          NAME: gitea
          USER: pek
          #PASSWD:
          SCHEMA: gitea
        webhook:
          ALLOWED_HOST_LIST: '*'
        RUN_MODE: prod
        APP_NAME: "Gitea: Git with a cup of tea"
        repository:
          DEFAULT_BRANCH: main
        server:
          SSH_PORT: 222
          ROOT_URL: https://gitea.pekware.club
          PROTOCOL: http
          DOMAIN: gitea.pekware.club
