apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncserver
  name: syncserver
  namespace: syncserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: syncserver
    spec:
      containers:
      - image: mozilla/syncserver:latest
        name: syncserver
        env:
        - name: SYNCSERVER_PUBLIC_URL
          value: http://syncserver.home.pekware.club
        - name: SYNCSERVER_SECRET
          valueFrom:
            secretKeyRef:
              name: syncserver
              key: SYNCSERVER_SECRET
        - name: SYNCSERVER_SQLURI
          valueFrom:
            secretKeyRef:
              name: syncserver
              key: SYNCSERVER_SQLURI
        - name: SYNCSERVER_BATCH_UPLOAD_ENABLED
          value: "true"
        - name: SYNCSERVER_FORCE_WSGI_ENVIRON
          value: "false"
        - name: SYNCSERVER_DEBUG_ENABLED
          value: "true"
        - name: PORT
          value: "5000"
        ports:
        - containerPort: 5000
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
