apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: syncserver
  namespace: syncserver
resources:
  - namespace.yaml
  - sealed.secret.syncserver.yaml
  - deployment.yaml
  - svc.yaml
  - ingress.yaml
