apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncserver
  namespace: syncserver
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs-csi-retain
