apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: syncserver
  namespace: syncserver
spec:
  encryptedData:
    SYNCSERVER_SECRET: AgAcrGckJYanQkL/v+5RzZ/EaS3qqllTovsVG75qSJoF2u/7XjPeIaRhCh86S3GFkB0d+9CTyYh5MvMyV/FUMBE6UyBuGj8lKpsLSZrj8izyVBOO2tFtzYMmkkRYeFewaHnhdZB8e3LHSAURoRZwkWq4eAZZgcKw/IYVDxSNvIsTH74sTeZCt84bDOUCmRw8ZasfEWt29ZNKnkc4Sz6AC7w4Snr/AZr3pfe0kFUJoeMexT7/h43U7lazgUn+mAquztrYB+2gM5sAAT12r+pUfCJgSfXK9KqfVK2R41XdCxDnre3kt/7ahgApkmhUF9h2uYp8bGtfFdm1lKDOcSPvoebpbb/Y5bYpzc6arnTPlC+SN0vogRa9ByKFXXQoMM6a8J3IB7g/wd+Yw6KbqxVoqNBWwl7waMwLxuhbddb+8uQjZoXzhaZSvSYg5T6yKqEqDbX7fO9MUXqJeKpep+W3fVj1IGfBwsYQWHHbMa3clRZYP3KxI+/MvGyVRiZEQVNRGljxB5zXJ1asHH4VjxKLWrC4H9lkGLetxINsmxbA46ailv0i/xPwasXhbMzXfrlvvlSmzCsK1kUMyJ40SJO0WBUz/GsA/f0xZyf7OyH0aHDYXndtznTXyZgLGiEsGMBGTCYQTtUoN2g6cD9BnNOnXAIA4vEkdEw6JGD5x4+y+YMnxovFw8YFEgHddN1C2xwd407bi19KkIz0+Gje8eTOrI3idWkH9tdQhoOaew9CvBYKlfYHd78T+k78
  template:
    metadata:
      creationTimestamp: null
      name: syncserver
      namespace: syncserver
