---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: syncserver
  namespace: syncserver
spec:
  encryptedData:
    SYNCSERVER_SECRET: AgBaj6l7kR5JsetK4Q4hy8SgQM85xHPL6zGog2ThbdANb7LlDpUgSwYeu+9pcLpPUa63Ixcyl3bkL68CLA4FChNDyjarbwbU1DIYFdhq8tFBTGuND2NHr6h4873zuKIG/CGWTQwJl7m44ru6sL2q2k8NK3cWoCZ9uMDBTLtUzN1T8atOmQVCsWqsZfXDWyeE9En08k5m/DJyf+Ft+BLwVqFde9YIWW3/+2uuvE1vwnyJpVZKPFutw1dgN/fuFqIY0iSDfYXKrc6KUYq0g1okSPrVeD7pjxKIhDMLmMYNCqJtOo+eP+zlXKFYhBqmc1bZY3c2iIPB4m3L1NXiamQXAQtWllfrI4MVjPtaOdW2DmrMvh1OxxOCGyofoFqsRvQY7YHwGGILUwbgTRkqHzyIWTorzm97OAteUb18rwjsBuPAf5RVTcjItvu42YbOvz/btgKoAqXf363Zw75b3qsAst/gndSfU+IjhsupsLxusHATH+L7Z8oGht5BUCJNPTDQpMl8zAw1vYPxAw2SLDGlpVitSZre/BM0UL9hpYTkaLSjOUdWIlDGQjd4b/MXgmxCeaDHdyDU6cJ2YWwLaqXK5z0TFkYCKV/SxTg4xiyuP+twyVqUcQGuhcXLo/h1uV47oAPn3LXpvs0J8Mvskf99BbBJJAkWjgO07UtoEKHkmYCv+sJY8Gfyvh7mWFxm+qqsNewv3wXEUIQija2f+OMsqBYzGgcvAhIdvQ8W8+YqbSRN4kUs5AfaD429
    SYNCSERVER_SQLURI: AgAMNczIXpDxgNjZnAWLKnmUnXmrHwgt/VgFfaSHp+oyD1jPlCKhcEtL4HprTve6QtEDUCz511II4U+BqLoZKEmXYYKLyZalwsMtv2mweZ0z666YZU8zvT6ZsnTmzOr5IY9LTCvXAORI+/I34VQQUPCsn70OLlPMvFjPZGyjY6Xmz5gVshvaNuKSgcAbw4LrzJP7PCb2/ftlhM1MRlJ9jVgds8ZhgKIVWQjcsT+OmPAQ+g9KA1AOyqKaZGSQxFtCa3NoOwLlTF0GaHTuqJrB8vaDb1U2JpL9TnvranfTmx3aNJcb8IPReMFnaHoXb7TFOGpy4QGrABt9hrT8Gw4jfvX89ezpePnUlXRtFsJTLhaD9T6OH+lyDw8VXZdTIqaHwjiTCulJ8A7GdVf8sOY7PxBllAcLBYdJSbMvDLG9F9hp511ftCPsbnpmiExqP+bP79Xnccds4BIWIJBCopuRsisAe1N3tp+XemFpRqK7KuobBniHveDwJUCvO4vyJAjvPfiH/WFkPge/rLSubRkDbIRnaAXpPVeZ2s3cq/O4UwSjtIIkvS5rskgEBvFHHoUSoLHvPxMTBaHqOcn4sHOEBcHKLubEGmbM70xsQEtGwSzHl2JkJO5HZN0ZN4f8jk64rVSOteiAJaiEGPLH4As64ZJ9NMPnvbPQMwtmFJI02VJ7T0Z2NdNIcozWx/exBqunpc/+xKLSEEPICtQ2XCuEK2l1m1G0x2mOv45JcnsAFqpAIhfdcO1PLLBRfgzJ0yV+Z80g0Z/ryba65iqMRouQM5k=
  template:
    metadata:
      creationTimestamp: null
      name: syncserver
      namespace: syncserver
