---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: syncserver
  namespace: syncserver
spec:
  encryptedData:
    SYNCSERVER_SECRET: AgAI7Z1jZ+CEnGsRC+OnHHYg8tUezM6toyD9xSKX8PB89/Ab2xKe52D4ZlHg2NCPCb64PS4IuScKXAKdROsEOA3OeGdo4tJt3hCjvEBIMRbVF+lfLuwzxRs7g+9KgJghTHRysZ7SHk2X9hx7KvixmQxhgio1Be+0yOqbdcuv9VNVX6cz0u7/1jBr9TRRZS9Pd4eO9mBTBQn9B73Ez+q0nnT6PG+y1WRPSnhMMYvU+kgHfariFlCguDeFFdaB7/4D6QtbnDkO9jA7gKApxPs0c1QGeN8hI8WwqDCClrWFYOjke3FAuBLKLLlBgx9gXUoEXk/3FLLwr8sjAALmwshhI9yzHWfEckuaJs1wzagIkwOUP4RCNdqwuW32AScwpr/YuXnIJmzN6yaG+wC9qkTUfvB+gy7+vRgyKdm0HOUpg09ZyF91LKlYVBNvGoOgOHlDMxlOhBsnbc10DoKX+OHF2nHwu+ZPrZI+5m85SVB7VGuFOqVXTXRiOR3fxustv+PInwDIp0CO6FYQENiWIEpP97b6RRVTpbqQQupN02fW/FwlRn9i3TYGzO0ZOUTdmA8NVyRPySshGTGkDLBzOYEtsTh0NJf+q/TGVW5VAX9qFzmHoa36mmPDWLxnmBLPAmSgcVSpmSYibz1C1NNEJqTN3Oa1qFkKiKhNtciOw9j8knYKax/XvKYQaQAHkPXlPzuXqcZ3Z3YccRcToiiXvYlQCl9BGCbaNhlmu1yShQxIs7/GCpfpmPWXN8at
    SYNCSERVER_SQLURI: AgB7MKGYMrxQnwoV9B4jDhG2bwQ0nnEFO8ma6bv+7cDEegxWAyKnWKdTPdRVl77GywYFmG7rSJgCoUDX2fKs0GUYeDRxSAYNhpD0Qt9/aUmBfyYz3R3ZOU+8/Q/Rmu/7/IUe+6L9yEblHGaIDugHMD3nOcWOx2XpSY6VPXa+qSaAqFv3qUszrf0y0QvyAbuYYld1pMDWuSbyCOXMOFYK3e2Ew21T/MdEAuVybdmDsR7HwXSQufHHzmMEkgoB6am0Oh/BpHGcO3oDpFPNsJVmcpYSHUq9cQouQ2AOn11i+XU4vmqyp9nE3uQYMhoTLAPsRjLbEQ5XOjlvEJ0YgN1wnkpq3kUQqkYFKWit/UEji1DDecHOxrVsaHRwOCinYdJjkg7zfyIkwhIErAdaJRbPsVOuYCAZB/OrL1V7hzGb/t/J80NbvbBg4faYHe1Qv+qPc6NZgIyBUOzC8s2rcrkFwiauAWy5crSg6dPe/DziJN2awjGV03jV9JqfHlL8VEb9cYpN8USwWkGRY68aS3m64hylUZ1/4137MDoYrNULrxAp1uBmTS9lEi88N7mckBfj3fvn1QI3v9lyG1CIRlqpKeC9N1EdcaLznDBku6HUWyY2+B0l1jD5RQxcwimrWLXXk1kkT67kD3cIJHqUvSIZhJA9y2jt1pr7/yHqduM8/GfehLohO7f9oV7ERNw85jHDvK+pABrBUgG8f+MczlrgdLQwNuP0Rbgw/v+n4mDu1bjnRniUhRW5+WI+iIiILYbint2iw6bx3oa+vjXRfmmKlFzlDiL2S3Hlq5A4XgbyZBS57+EEYYPTFn8=
  template:
    metadata:
      creationTimestamp: null
      name: syncserver
      namespace: syncserver
