apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: gitlab-runner
    namespace: gitlab-runner
spec:
    values:
        image:
            # https://hub.docker.com/r/gitlab/gitlab-runner/tags
            registry: docker.io
            image: gitlab/gitlab-runner
            tag: alpine3.15
        imagePullPolicy: IfNotPresent
        gitlabUrl: https://gitlab.angryllama.net/
        ## "group runner" for gitlab.com/pekware/: https://docs.gitlab.com/ee/ci/runners/runners_scope.html#group-runners
        runnerRegistrationToken: ENC[AES256_GCM,data:IdhqfoFbD84SKgTSaDyaPYt00uxsIFJXpNbhf3Y=,iv:KSEjj6hXSFfR4d0C8LNZ7pDVhKkJ7GBg8I7t4BKby6I=,tag:S/hPsijREYQA+rFvhqMF8w==,type:str]
        rbac:
            create: true
        runners:
            config: |
                [[runners]]
                  [runners.kubernetes]
                    image = "ubuntu:22.04"
            executor: kubernetes
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-01T14:23:28Z"
    mac: ENC[AES256_GCM,data:VB4ru32AuTFBF18mNML3Z4RNvOdQz4bfvL709Man9yhAGW5yNgKArp9aDGiRJvni5JxOTbHfs9wbVBLrCTqm0Nt+AUmh0qefTyIzZyn9lSLQfO7QBguR6QV2Lhs+/nSBBImTwKGrcHG3pfs86UgT286pE2xIQ2h/xT/CYkP43Wg=,iv:28gzXq1IoEmpRYi5Gug2fWuTcbqV1f4LzEe5D5Jiv6w=,tag:HGYzmRx2haE71UdGUOXJ3g==,type:str]
    pgp:
        - created_at: "2023-04-01T14:23:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA39JIzDKQyQnAQ//VLH4wwkAJt83TZLQ6WOahtWmB3/jOQFERYkiynyZXBhq
            5N6B9WQ9YcRdsNto68Mm/VyHYm61PEaho1622MDS/+YR5Hq0llvkfs0HX7KDIdVO
            4koiRj996MtqgzxmCmoxtYEkTO1KGsSsidw8ZBV6Bng4WUd6b9ze3hLxnX25FJQ8
            sAlp6YMBGuhU6+KguWo/3Ve8Uy9n5KS2nggHrG3H9SnW3UEUGUN+fxeZOMG+QsLp
            X0lYgC8y+792grr1AJdsQmQWUiGim2NFnYNk5lSsKbK0Nnrpng7h3/kpOanViP7m
            wzR3n8BWON76gZQapnt+vI6hURDyQz451bb7AwcAIb7t8T9ak8Tnb7h9xFTGijE6
            lPfydw2zJxpNXjwzEVzUU2LDYDlQtKFlaRm29ODEUwTYlwTR1HQRRS98kNco/O1P
            wz1iK5vLUgG8IvgtLOA5hwMfbU3uRHrlWLgGGptYjrMF7Mk1EY4r41t6Jz8TyhL1
            f3xOxVK9LEl8gbnIwGApnCUcpCcuPP13jTOrMT28x+rv76KUEnLFpOU2BLiQVHen
            T4QosHH2EHRUstloUPy1HbuHa18vkze7wlMWPt+aboesbKdHAFFH9JsSrrDI+K8s
            1GabFfYQ0JeFRklhppTjnnRYPHXwKh/LEdv2HcwerN5VEbHoao4uxRnbhuXMDmzS
            XgF9NDlVAi4c4A2/swCQbWJik/LTCdjdbW1j1e2RNWjuCFU0m70b0j725mpi8meH
            kBtTYCIytBqzjuqrX3k3z/aynBPpiMgBU7whgaRJ1aZ9OqFlTSkkbaqh1R184iU=
            =nBOy
            -----END PGP MESSAGE-----
          fp: 2BBD3786044CFFE0260484332213C1FB5FFCB338
    encrypted_regex: ^runnerRegistrationToken$
    version: 3.7.3
