---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  values:
    controller:
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-prod.star.home.pekware.club"
      replicaCount: 2
      service:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "ingress.home.pekware.club"
    tcp:
      "5432": "bitnami-postgresql/postgresql:5432"
      "6379": "bitnami-redis/redis-master:6379"
      "222": "gitea/gitea-ssh:222"
      "3306": "mysql-innodbcluster/mysql-innodbcluster:3306"
