apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mariadb
  namespace: mariadb
resources:
- namespace.yaml
- sealed.secret.mariadb-root.yaml
- sealed.secret.mariadb-password.yaml
- mariadb.yaml
