apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: false

  username: pekware
  passwordSecretKeyRef:
    name: mariadb-password
    key: password
    generate: false

  database: mariadb
  port: 3306
  storage:
    storageClassName: nfs-csi-retain
    size: 5Gi

  replicas: 3

  galera:
    enabled: true
    config:
      reuseStorageVolume: true

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  metrics:
    enabled: false
