---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-password
  namespace: mariadb
spec:
  encryptedData:
    password: AgBpLZaKxFQOccVfWppJsW4uiNg+YA6Y+XjD8ozMRqyvKq40iPe08Stq0ImIvVPvMFNEfmNV41FmSvLHctsiptQNftVWgqYJo7G8ipAE9qFXyCfv+pDhV6pljBIav0vHPNwBJt7y5CN/wLiqnqJlRh2HCFGokx03rXW8b7oRcQaPeS+EuRdOY2+4iUrEZXdm4e50KAjZYkW0LzzfEiLeqs1BiGdR76owMcVq1ZIChBAxINcF835H2u6MsEh/Nw5mYpcauXsxIf6R1HsI3TuXdK3p2FSdumkM4WEENzRe45KmFYTUQuF2bzkrYddzUtGXmF0nJ+eaX0YK9kXG1XB3/AbsWH7pSgwX7DAI6TtaU59BFNwzUwSGJHJRpAAdRTLRbMRwYoR8i3agYgZUrnwNt3MeamQc+La6/0NbZYOVcGRMPjwqXH/GYIwwI+dK/UebbeGQCgg3u9Ug9Duvw8hidl2o4ojmm3f6+0w5Oi+4/tJWn56kzZT0XPBhuESS9oeyd7MlsNKteZTsbYtSFwYPboHXsxKLUgL/ijNwDAOuea6sbe4zqezIWLZT4iRCKJ0Pl1IzGAw8tFfek/xlVFEx5+hTmsbKRosdAIdxgNxrRbxq6yFvcdoBftlkvx2cl2VY2pUxJSu4RAFJnbeI0UGTuBfY6hevOyq4ZR9Ev6rWsD1e+p8pxfQtxsOnLXy6FRLfWMVl4SiWN141SYgz5PCphDo5
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-password
      namespace: mariadb
    type: Opaque
