---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-root
  namespace: mariadb
spec:
  encryptedData:
    password: AgCZrJoGDf9uEWPivo0F9NzLs8cd52E0BiyACn9Ys8epNIxa9813QYhh7vd5AyvHWh2AlXT4LI9/ET4Jk9HOXyysUMaw8DS1uLCEqs0VlTsKPcNjvb3jzHEO0o94jB3E7iJgllAf2y4fAQpJosZqTB6FjYCH4t7Fa8zXbWtiOGqwwf9WOjE594kTUS6aQcufRtAruOvarmKD9jQ2qC/c7hSx/wY7fU/LKxmCEjgXy0e3L+sd6gDVx+H8RVMz4Q0GRQRh+Ppg2WoDXNWR4VRDCHKCjHolOx69zgKDsbRNKbWOzSUpKrtSHn30u4NlMutw/FShxjK1zF7/LkZfhmb2kNQZPOFxDuuNr6zq3CCBUmn+v3vZEu8egPQR/DUuE3g/8GJ12vKx0hkwXQaMskWN9EMw5zwMJVElOXzM5nHv/xa2jfcrZVvkK2OdpWUhh9Ghmg1S9S/B7X/jvBDvgVWgx5T6gKdmDFuIdjM9AAqW3EulGbEGOsnCapN4rX7IpyLB/OagAUYB5eylIVyIoPp2Qvk2HVsSWKEdTt4BMaGV0ubSE2p3S3uX4OP+pFeZaMIT5YNDQA/hXQrw+hJ7jigc3I90mPUwiL08wp7tdJXvjcfkJVwizYdsWw48RRzR8MYmhY8PxW2hyUTVQvYdtV4UIoP4dc89p+eBa5gqkU+6/5m12BOH6H3g3ZyCNbRT5gzlZ7wBRkJwclZ3ONYm8IIpCT10
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-root
      namespace: mariadb
    type: Opaque
