---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 120m
  ref:
    branch: main
  url: https://github.com/fluxcd/flux2
