apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: drone
    namespace: drone
spec:
    interval: 5m0s
    chart:
        spec:
            chart: drone
            sourceRef:
                kind: HelmRepository
                name: drone
                namespace: flux-system
            interval: 5m0s
    values:
        image:
            repository: drone/drone
            # https://github.com/harness/drone/releases
            tag: 2.13.0
            pullPolicy: IfNotPresent
