apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: drone
    namespace: drone
spec:
    dependsOn:
        - name: ingress-nginx
          namespace: ingress-nginx
    install:
        remediation:
            retries: 3
    interval: 2h
    chart:
        spec:
            chart: drone
            # https://artifacthub.io/packages/helm/drone/drone
            version: "0.6.x"
            sourceRef:
                kind: HelmRepository
                name: drone
                namespace: drone
            interval: 2h
