apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
resources:
  - sealed-secret.do-pac.yaml
  - clusterissuer.yaml
  - certificate.yaml
  - clusterissuer-pekware.yaml
  - certificate-pekware.yaml
