apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-dns
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgBKQKQieBHjVa3HgB09yg+X1NjiQrokJwXJxV2H1wK1OzHzJ0ttGnNplw6ULyy8JDsyDM9z0HpSEaF9DgZ0DaBbiL7Al+Pft0bPhVLzZezd1iQwULrWnE9BWvsX2jy3nJT9McQ0Y8c9QINVIxHs+Ezt+dgwn5mHbsHODNxDPIo4sWRpRIyyD19Br/umqe2cG0Jar0aAeJ/ecUyY7vzgd9TBCfF73/fudb6nxiaCSoQhmt22cLExZ89lOyJ9XRMiHoBtfKWZ268sYY47hsR8Qx7zav2PwEST2dic9Xy+9eDYyepE19/blE7KPSdN5TLc6gTJe0RGZ2TyhqqbxQ4luxSetNWmPPeQn2vHM1TTU/pyHhcTZNo9u2mPezIWeVb/CRV+XW4wrkyKX+Wd3dcrJdZdhVuSnwg6dy9oHag4mOqyCGf9mItLhKF4FL6Yl+WLye22DwpakK6aPcNqvwSYunWPI5WxzsUF60qrzEpLSdUvvfYnj1/uOIksNsMAkNkZfEGg+BTXUCcr+IQn/ah1vIFhv7f9JAfrFm/3IJwqTCO96Lcuw0W2YOgNlsb3hc756z1ZRxl3Ep6GIuCGOXkBMkSe/WCWYZzZyHx62m58Pu7zphWu+G+GP6XfI1FV9F8toaAd+6460T44bJIwmwnMZQV9PNxu8lME+4M3le4KoIcEk7OukYVY4mOIHyxZk9KTMv4B2Xyn2NeGb3hVBY4JTOE9I/JflgVqaWUYGqA56jMns2cYKgQszJLe4JuUUc8q5uji9WjljIdx2ttQsH8b858SRMV+/s5T+A==
  template:
    metadata:
      creationTimestamp: null
      name: digitalocean-dns
      namespace: cert-manager

