apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: drone
  namespace: drone
resources:
  - ../../base/drone/
  - sealed-secret.star.staging.pekware.club.yaml
  - pvc.yaml
patchesStrategicMerge:
  - release.yaml
