apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mysql-innodbcluster
  namespace: mysql-innodbcluster
resources:
- namespace.yaml
- sealed.secret.root-user.yaml
- innodb.yaml
