apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql-operator
  namespace: mysql-operator
spec:
  interval: 2h
  chart:
    spec:
      # https://artifacthub.io/packages/helm/mysql-operator/mysql-operator
      version: "2.1.x"
      chart: mysql-operator
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
        namespace: mysql-operator
      interval: 2h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
