apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-prod.star.pekware.club
  namespace: cert-manager
spec:
  secretName: acme-prod.star.pekware.club
  issuerRef:
    name: letsencrypt-pekware
    kind: ClusterIssuer
  commonName: 'pekware.club'
  dnsNames:
  # 'home' is temporarily getting certs on 'production' tier's behalf
  - "pekware.club"
  - "*.pekware.club"
  - "*.home.pekware.club"
  - "*.development.pekware.club"
