apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-dns
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgBMzBXMufxLgmoM1Oog/13E+Q+duQ68wYdSNEZc8M1mveU0Vabpq4WzDD5rZkTfRgErL4cxIgCuoXOxwQbE9A6rv7goZAl1MNghL36pqkwgk24iUBMtRe0T8WSJxkSAYfCCEN4FJCGDAH7LdiSmWAEmoIBTe3o1TiOA0fA+rmIVfyCA/ylCRoRReeuPsE6PqVruG0U22PvI2zISXe9JAeXlNuiVGgIg17LFcCTBYklojT7c24dqFycz9Tp1Rpz1Jwv/1A5n8LdlOblS69/uRHzEmFPDCc4YFqVVcIZCsNqXGUb8EqqJVHFiC9QgKte22eflyT/X2Da9qVxzKSCs684rusvMml8z0bwrGbD/j+yVo8CdbF/DX2O1g1IiqasU3uyIu8cQ4ORIhGcdaqCm5eIIyhJ87sgsuhmCpVtu0Ug1npS8Wmb/4QUwnWkMlaJnSoDRkTB/c5vTihtS+7E1FPzxCTYSG5DEsop0EanjwBhvjxIF19he2QQFe8UFHiPt8OoB3QptQ3iDhoaQ3jJR2fBjWBKJ2/zO5hV5SxzywBdujd+M+p4qB9C7XtE6YlsLZHEcd8YXdUxdKcAhjJQSFs0lrK5NhMNffcTcazivSIlilVeElkhbPIQfYALgyfIY4+TbcRcA+VFB/dAQ1SEZaTxDyA5LYzm3GJRUhZmvckucSaFvq1NUvvxldcIoIESr6cwPvni8I4jHXwWkGtj5YU1AMGU7jopNeGE3eADqb5L/Q/mPjOmd22mfwMXKHqCEwOtRqq3/HGkyamfqA0QhaAuhB00M40v1TQ==
  template:
    metadata:
      creationTimestamp: null
      name: digitalocean-dns
      namespace: cert-manager

