apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    ## L138
    ## https://github.com/fluxcd/flux2/blob/main/manifests/monitoring/kube-prometheus-stack/release.yaml
    ## https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - kps-alertmanager.pekware.club
        paths:
          - /
        tls:
          - secretName: star.pekware.club
            hosts:
              - kps-alertmanager.pekware.club

    ## L711
    ## https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/service.yaml
    grafana:
      defaultDashboardsTimezone: cdt
      ingress:
        enabled: true
        hosts:
          - kps-grafana.pekware.club
        path: /
        tls:
          - secretName: star.pekware.club
            hosts:
              - kps-grafana.pekware.club

    ## L1909
    prometheus:
      ingress:
        enabled: true
        hosts:
          - kps-prometheus.pekware.club
        paths:
          - /
        tls:
          - secretName: star.pekware.club
            hosts:
              - kps-prometheus.pekware.club

      ## L2282
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
