apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  values:
    strategy:
      type: Recreate
    clusterDomain: gitea.pekware.club
    image:
      repository: gitea/gitea
      # https://github.com/go-gitea/gitea/releases
      tag: 1.20.5
      pullPolicy: IfNotPresent
      rootless: true
    service:
      ssh:
        port: 222
    ingress:
      enabled: true
      hosts:
        - host: gitea.pekware.club
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea.pekware.club
    persistence:
      enabled: true
      create: false
      claimName: gitea
    gitea:
      admin:
        existingSecret: gitea-admin-secret
        email: king.phil@gmail.com
      ## https://docs.gitea.com/administration/config-cheat-sheet
      config:
        database:
          DB_TYPE: sqlite3
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        webhook:
          ALLOWED_HOST_LIST: '*'
        RUN_MODE: prod
        APP_NAME: "Gitea: Git with a cup of tea"
        repository:
          DEFAULT_BRANCH: main
          ENABLE_PUSH_CREATE_ORG: true
          DEFAULT_PRIVATE: private
        server:
          SSH_PORT: 222
          ROOT_URL: https://gitea.pekware.club
          PROTOCOL: http
          DOMAIN: gitea.pekware.club
    mysql:
      enabled: false

    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
