apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: drone
  namespace: drone
resources:
  - namespace.yaml
  - release.yaml
  - sealed-secret.star-pekware-club.yaml
  - pvc.yaml
