apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone
spec:
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/mnt/pool/volumes/k3s-home/drone"
    server: data.pekware.xyz
    readOnly: false
