apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: drone
    namespace: drone
spec:
    interval: 5m0s
    chart:
        spec:
            chart: drone
            sourceRef:
                kind: HelmRepository
                name: drone
                namespace: flux-system
            interval: 5m0s
    values:
        image:
            repository: drone/drone
            # https://github.com/harness/drone/releases
            tag: 2.12.0
            pullPolicy: IfNotPresent
        ingress:
            enabled: true
            hosts:
                - host: drone.pekware.club
                  paths:
                    - path: /
                      pathType: Prefix
            tls:
                - secretName: star.pekware.club
                  hosts:
                    - drone.pekware.club
        persistentVolume:
            existingClaim: drone
        env:
            DRONE_SERVER_HOST: drone.pekware.club
            DRONE_SERVER_PROTO: https
            DRONE_RPC_SECRET: ENC[AES256_GCM,data:hN11+xKl6uC5q04b7ZBalvfhO9R3jnomKXGmbAXgEzI=,iv:w9KFJMGEgAUumKmqG0d2CrL5iwU0ZmOdJ0ezzmgDAp8=,tag:PI25cgPn1fcJTfXcws6N5A==,type:str]
            # https://docs.drone.io/server/provider/gitea/
            DRONE_GITEA_CLIENT_ID: 7e1cafe2-f8d2-4b55-8dac-1df26492ae85
            DRONE_GITEA_CLIENT_SECRET: ENC[AES256_GCM,data:GCgnzJ0dInwEcYAW6rp54qlxUkJ4GrUYlDYB7nvn+UvhaylTtmBkwIghCPc=,iv:hOuzmNVnwg3RhQR9lo+Rg6J46lqNrl/nSDPc1jca2Fc=,tag:HfItYJjUA0zMbqR7AG5CdQ==,type:str]
            DRONE_GITEA_SERVER: https://gitea.pekware.club
            DRONE_WEBHOOK_ENDPOINT: ENC[AES256_GCM,data:LZQFCWP1h62RfvHX0r/T/d8Rs6d7twUntsS1cBMuMPrSuA==,iv:vmkXsKJXZBhokIJn6VVi3fSmbOB5hZzRy1Bs/QHNs/w=,tag:Wec6wgFoA6skq9Bn6v6v/w==,type:str]
            DRONE_WEBHOOK_SECRET: ENC[AES256_GCM,data:u8MvLt1xpT70mNsx,iv:MHjGRdh1uZOZGF1w7/8+gQUPQsMBD+Zg26AXULwxF3A=,tag:vwkVUxY2geSvZrFtKFhKRw==,type:str]
            DRONE_USER_CREATE: username:king.phil,admin:true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-05T20:48:56Z"
    mac: ENC[AES256_GCM,data:6SmkQqPTn2p0Ur4mm2Lgr1Z8aoma8ESxVfYvnaCm1xQkLc6hQ9KejkpYNYwWRm97DEsCn4AptWJxhOhIaZeSYZhAySYYWxRD3zPR2qBkNO1FKvTg3XlzEi/A7V/Nj/0s5VXZQ3ADFjQQGXhGMh/oxce2RQn3hYBp1WjVBlT9+u4=,iv:F3QZGFonXe//oai8nTjKDNlPAsCDEaDX5rmGHRqFt8M=,tag:TRE5uHHqjibug1RcY4kRlg==,type:str]
    pgp:
        - created_at: "2022-07-05T20:48:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA39JIzDKQyQnAQ/+Jb3QvVgJDlWfEzn2nZhX+cgrXu8OlW1MiGXCaB0mgr3v
            o67t9add6EfQttee7NAa76KmOGhUffQUSnkqMHldiAnIRkJwiK1uQulxtIHQPmuk
            gL7VXMWRFqZIizZB3aRdmtiDA1+dMF62YKLMwWVyLWT1VES1f6BvmrYOYEXO9JmA
            oCeB3RYx6lV1oCb6bE/riqbtpxl9f6aBpFQ5y+gglUhsSDcceahgyB7PAssj7EAo
            buMfJUZwO5fTSFF8HibepRChPmJJ9GM1fEUl5aq2kdi2fLuaVfkIp+IU86v+N664
            pyfXvqMeYEIo22DaWir9zdJKYqeyYkDXaxSj0degaSm4x5JaM5GSCxv/g2LIicns
            Lt2KlE7nlry69FPY4bz7hFvVQXHMJwiyZS9yFJbbOKIjprc4Aa5uwnVvf3yaG16W
            xuvfNMlrDsFYSyILlrgsTX8Pdjdqf5HNumJEiULijwQ4tIGD75pnxW2W3m1HvTF2
            dqrqdSKmc/XhKWnaSVp2ed53/AKCGSRPPBhYt4K5bxVZT+IkgK7Wm9gWmsZaHH/i
            oysTER16fAR6QcJxhNfYicIj5oh2E6x5ExfY8oETJ1ZjOTYccQ44YvEs4g4UieXy
            a0aeijniZAvn6WG3Nxmc45F6WFQINWPqfgm56wzqVXZaM8p+Zvb1P35z8AuOM9LS
            XgE1nLar7RMs2LLsX1uh6JuE0hglorj0czlIWT49wAsSLRls6+8wyzfwPsRy7CuY
            s/9QmomyA1V5FM2SqTT7tdyaUQZAiD2DsQiXwynjs/uUcQ71BDnZMkUKxPVDGGA=
            =fbOI
            -----END PGP MESSAGE-----
          fp: 2BBD3786044CFFE0260484332213C1FB5FFCB338
    encrypted_regex: ^DRONE_(WEBHOOK_\w*?|\w*_SECRET)$
    version: 3.7.3
