apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: drone
spec:
  interval: 5m0s
  chart:
    spec:
      chart: drone
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: flux-system
      interval: 5m0s

  values:
    image:
      repository: drone/drone
      # https://github.com/harness/drone/releases
      tag: 2.12.0
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
      hosts:
        - host: drone.pekware.club
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: star.pekware.club
          hosts:
            - drone.pekware.club

    persistentVolume:
      existingClaim: drone

    env:
      DRONE_SERVER_HOST: drone.pekware.club
      DRONE_SERVER_PROTO: https
      DRONE_RPC_SECRET: 60643fe8e71373bf5344f0f343918aa1
      # https://docs.drone.io/server/provider/gitea/
      DRONE_GITEA_CLIENT_ID: 7e1cafe2-f8d2-4b55-8dac-1df26492ae85
      DRONE_GITEA_CLIENT_SECRET: PXoM3a91TEsu47N6bq9NJG3XSN8wslV8nUiPe6gNtnHg
      DRONE_GITEA_SERVER: https://gitea.pekware.club

      DRONE_WEBHOOK_ENDPOINT: "[redacted]"
      DRONE_WEBHOOK_SECRET: Ig@mz@QKw3jf

      DRONE_USER_CREATE: "username:king.phil,admin:true"
