---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitnami-wordpress
  namespace: bitnami-wordpress
spec:
  chart:
    # https://artifacthub.io/packages/helm/bitnami/wordpress
    spec:
      chart: wordpress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami-wordpress
        namespace: bitnami-wordpress
      version: 22.x
  interval: 2h0m0s
