---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-wordpress
  namespace: bitnami-wordpress
spec:
  interval: 2h0m0s
  url: https://charts.bitnami.com/bitnami
