apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../../base/podinfo/
  - sealed.secret.star.development.pekware.club.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
