apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo.development.pekware.club
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - hosts:
          - podinfo.development.pekware.club
        secretName: star.development.pekware.club
