apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m0s
  chart:
    spec:
      chart: gitea
      # https://gitea.com/gitea/helm-chart/tags
      version: '5.0.8'
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: gitea/gitea
      # https://github.com/go-gitea/gitea/releases
      tag: "1.16.8"
      pullPolicy: IfNotPresent
      rootless: true
    service:
      ssh:
        type: NodePort
        port: 222
        nodePort: 32500
    gitea:
      config:
        repository:
          DEFAULT_PRIVATE: private
    memcached:
      enabled: false
    postgresql:
      enabled: false
