apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: ingress-nginx
  install:
    remediation:
      retries: 3
  interval: 2h
  chart:
    spec:
      chart: gitea
      # https://gitea.com/gitea/helm-chart/tags
      version: '6.0.1'
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 2h
  values:
    image:
      repository: gitea/gitea
      # https://github.com/go-gitea/gitea/releases
      tag: "1.17.2"
      pullPolicy: IfNotPresent
      rootless: true
    service:
      ssh:
        type: NodePort
        port: 222
        nodePort: 32500
    gitea:
      config:
        repository:
          DEFAULT_PRIVATE: private
    memcached:
      enabled: false
    postgresql:
      enabled: false
