---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: descheduler
  namespace: descheduler
spec:
  interval: 2h0m0s
  url: https://kubernetes-sigs.github.io/descheduler/
