apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: bitnami-postgresql
spec:
  values:
    global:
      storageClass: nfs-csi-retain

      postgresql:
        auth:
          username: gitlab
          existingSecret: postgresql

    # https://docs.gitlab.com/charts/advanced/external-db/
    # "PostgreSQL 12 or later"
    image:
      registry: docker.io
      repository: bitnami/postgresql
      # https://hub.docker.com/r/bitnami/postgresql/tags
      # https://docs.gitlab.com/ee/administration/package_information/postgresql_versions.html
      tag: 14-debian-11
      pullPolicy: IfNotPresent

    architecture: standalone

    primary:
      service:
        type: ClusterIP
      persistence:
        enabled: true
        size: 8Gi

    # when 'architecture' is set to 'replication'
    readReplicas:
      service:
        type: ClusterIP
      persistence:
        enabled: true
        size: 8Gi
