apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitlab
  namespace: gitlab
resources:
  - ../../base/gitlab/
  - sealed.secret.star.home.codemonkeys.site.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
