apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  values:
    global:
      edition: ce
      hosts:
        domain: home.codemonkeys.site
      ingress:
        configureCertmanager: false
        provider: nginx
        class: nginx
        enabled: true
        tls:
          enabled: true
          secretName: star.home.codemonkeys.site

      psql:
        host: postgresql.bitnami-postgresql.svc.cluster.local
        password:
          secret: postgresql
          key: password

      redis:
        host: redis-master.bitnami-redis.svc.cluster.local
        password:
          secret: redis
          key: secret

    certmanager:
      installCRDs: false
      install: false
      rbac:
        create: false

    certmanager-issuer:
      install: false

    nginx-ingress:
      enabled: false

    gitlab-runner:
      install: false

    gitlab:
      gitaly:
        persistence:
          storageClass: nfs-client-persist
          size: 50Gi
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
      webservice:
        minReplicas: 1
        maxReplicas: 1
      kas:
        minReplicas: 1
        maxReplicas: 1

    postgresql:
      install: false
    redis:
      install: false

    minio:
      persistence:
        storageClass: nfs-client-persist
        size: 10Gi
    registry:
      hpa:
        minReplicas: 1
        maxReplicas: 1
