apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: ingress-nginx
  - name: postgresql
    namespace: bitnami-postgresql
  - name: redis
    namespace: bitnami-redis
  - name: minio
    namespace: minio-operator
  - name: csi-driver-nfs
    namespace: csi-driver-nfs
  values:
    global:
      edition: ce
      hosts:
        domain: home.codemonkeys.site
      ingress:
        configureCertmanager: false
        provider: nginx
        class: nginx
        enabled: true
        tls:
          enabled: true
          secretName: star.home.codemonkeys.site

      minio:
        enabled: false
      appConfig:
        object_store:
          enabled: true
          proxy_download: true
          connection:
            secret: rails-storage
            key: connection
        lfs:
          bucket: git-lfs
        artifacts:
          bucket: gitlab-artifacts
        uploads:
          bucket: gitlab-uploads
        packages:
          bucket: gitlab-packages
        externalDiffs:
          enabled: true
          #when:
          bucket: gitlab-mr-diffs
        terraformState:
          enabled: true
          bucket: gitlab-terraform-state
        # ciSecureFiles:
        #   enabled: true
        #   bucket: gitlab-ci-secure-files
        dependencyProxy:
          enabled: true
          bucket: gitlab-dependency-proxy

      registry:
        bucket: registry

      psql:
        host: postgresql.bitnami-postgresql.svc.cluster.local
        password:
          secret: postgresql
          key: password

      railsSecrets:
        secret: rails

      redis:
        host: redis-master.bitnami-redis.svc.cluster.local
        password:
          secret: redis
          key: secret

      runner:
        registrationToken:
          secret: gitlab-runner

    certmanager:
      installCRDs: false
      install: false
      rbac:
        create: false

    certmanager-issuer:
      install: false

    nginx-ingress:
      enabled: false

    gitlab-runner:
      install: false

    gitlab:
      gitaly:
        persistence:
          storageClass: nfs-csi-retain
          size: 50Gi
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
      webservice:
        minReplicas: 1
        maxReplicas: 1
      kas:
        minReplicas: 1
        maxReplicas: 1
      sidekiq:
        minReplicas: 1
        maxReplicas: 1

    postgresql:
      install: false
    redis:
      install: false

    minio:
      persistence:
        storageClass: nfs-csi-retain
        size: 10Gi
    registry:
      storage:
        secret: registry-storage
        key: config
      hpa:
        minReplicas: 1
        maxReplicas: 1
