apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  values:
    global:
      edition: ce
      hosts:
        domain: home.pekware.club
      ingress:
        configureCertmanager: false
        provider: nginx
        class: nginx
        enabled: true
        tls:
          enabled: true
          secretName: star.home.pekware.club

    certmanager:
      installCRDs: false
      install: false
      rbac:
        create: false

    certmanager-issuer:
      install: false

    nginx-ingress:
      enabled: false

    gitlab-runner:
      install: true

    gitlab:
      gitaly:
        persistence:
          storageClass: nfs-client-persist
          size: 50Gi
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
      webservice:
        minReplicas: 1
        maxReplicas: 1
      kas:
        minReplicas: 1
        maxReplicas: 1

    postgresql:
      image:
        # https://hub.docker.com/r/bitnami/postgresql/tags
        tag: 14
      persistence:
        storageClass: nfs-client-persist
        size: 8Gi
    minio:
      persistence:
        storageClass: nfs-client-persist
        size: 10Gi
    redis:
      master:
        persistence:
          storageClass: nfs-client-persist
          size: 5Gi
    registry:
      hpa:
        minReplicas: 1
        maxReplicas: 1
