apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgAqzrtlKz+Pye5KZM7dFlo4oPY7g/VngefzXwSAWPuQxHgmImmZ8VBphkz9FzoPr+Gr3E3KNsosMlLXUp5TaBEMfziWfY+9cNoU2kxtVh9CA93eiESYYE6tFSI2fsJU5iu/iHJe9WAywR2jeIay4ilF2ZDJuERiaFIQTNdrjqK1mvEB36WAnavh89RVVBiFTbITkbvQvTJx/jQbijnrIgyx5szR4COmUepT9fMKMI6Hjl0Ttd8nguRN6OP40xl56buTr3KS1jxMNyaELQP/lY4AczXXbQaBoGOQUfv0DzF3/Y9riLbV3warKfyra+NFU+V3BeTiMT8Q54OVMtwJ0MB8gblJtxVl+yfKyuugv8hRmeIFRrKZW8wNpFm2uMmz4Xb58T6NUk/3aOF37eo234nOH+8BXjVYV3mPrXILpLfRjttwhEGpZupqSMk7ZJ8T19el2EfYphvBsqUltlglUMGXsEAjjDb3WPwVeOYo+Zu7tbu0ISBGuKoUTYWOo0MCoCMVFBKFeFGeO3DIN6eXz5p6mJ010HxbeboF04bSoU4SPTQC9JKghFjVsipzO36nv66ylNElKAorGwcukQhT6zNzmVdDGyoEmMbQFIu9vGfh/ixLQei7ydeVLv7hUqfYI5w2rnJ2Nnpgwi5t/VTgyo0V9TxqC+Vw5xVM+ZQcYSGXzytNTIEqBcxiY1AydpFgSyzBr8AUUF3N0A2wan5zQMHhrf7wMf4zsmFSpcLz+rOGNMnmGMBYCYjQf7nDE7b9KjGqOVENOTyW3JsbBA9YOAT4ERv3hdpYlznGwezKzAq11KczgkNAKx6E+rsTSLT/e9mXG/YEskksVFFcRDV8HckPbw6+BlBYpzUQU0vpQupEfZeu6L3SDgJVGa36Z8/IQbnrwLjTEV4PLiAfMfOFFuZuGsmgZ/cyALsRIsTm77mL682FZa2s1gJuLfG1//diJl0Rho0fvD3VXCpHXKxYKaaadThRYIHjmVKWWpwm+ltLBcDMeViu8DV58fDI1ic9Q42T/CEO5LGgtiKkK9QWmBDbw9Z9XgtpHkQHSgaz/9ww2/JCZOH/vSWPdhvjSyWiJquqjaX9rczi6xU86SFgdSXxYGlRqQkgKXUOgcz4N52cWLKk+JSRs/iSnO0iYApHmy5rAp9MzBXhunhtK9RtNMt1H1SsvNYbX+V9n5mlVc3kPmkwKCmXD12EIFjPUaYI5PmsU+qALoVtMPSq3jrUy6Pkj/FN50X+Zewplj8T3U36nwyL36pDH/6Sqq+XnvB19/849M821lMUnoS6s9dPLDexAre/ioB9bC8W1GddQxTmfuBd6wbThdqVytnK9URXUmyqKRLMPRIxbMQebLZqsBBw+ugYQLdaZgtSH6zPpqosVcDC82UcHEGnQ5HA750p+YZOFuogZHN7a3Qhq11iYnnkm9rkHXjEUfixpSLlIT+G2G+0XyTpOJjXLVJqIKSYeOqBnxLo8e20mi6U/OnA
  template:
    metadata:
      creationTimestamp: null
      name: registry-storage
      namespace: gitlab

