apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: gitlab
spec:
  encryptedData:
    password: AgCG28PgCinJo1LmSAZ8aR502RfeTjEh5p4AcLIVrnWf6cJlps42wd+8fsl3/LSJdTuLMv9sH6aovvsqOXwOPMehl2rGO4Wj1UkSsE/oiVsu97/mIrrnw9aFhZ7rgBxRoTUcz+mEjuwD8LGYb3n0uv2ZEifFFnMgNzpI6ZWvoHR3RtGBtotd/x+l8g+xY7FpHEwzNJndH0QMOQe7Hrdr93Z+ACjEPQ8F8PBVkNO3ZqZmiKS5WldwzmrW6MRq77mMg+xwW/0wBw40DED9HGMBWKx4eJOGRfmv5joC9MbCLQHbxaPfxJHdjKPD7fyvqdHHmES7knu8i5i9kI7z0+fvGQhu9zGpdqs/FUVVt+I6WHMBAiIUV/n0tqMjID49D8Aqk+FKd7eEKtkWHceMTuhL/73TJZRh84DFDKc6Ii/hmMsWmEsvJsFOfjnnH1rSOIdojI+KScLgjAaVvLu5lt0I88t9sk7k8Q8SCRdMFBzSzpgnrxEljfKDSDR2JVE2jeqySqmXWxWL7h8DA0ZUdSc87QvXHArvpWY+tHrt4Ui6Vl5gJKsndONDn237ssK30gr9M6/kLeXW0y5wlCo5rgSDrG6LbcRLdQBI+JzdTpsp4m+6PeEcriXmmOKDRxteUKKs7/jWfs5Ht2hzoflot0CKINfLvLp2X0J30S7z5Txipl3SAzRX6nG4hEzLNmFpRgRqTwa8XCiyEtn3TA==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql
      namespace: gitlab
    type: Opaque

