apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgAD6lyhVayg3DgRunOxGE0jsomht1TsGbsP4HQzgBJ74SMB2oH+Dv1l+7koAEW8PSYhulEd6v207y7d/UDMM/Q37vqBG7ayToNJYVDlxhyTUw5Qgxb5Lf2s6F7CBRJK+HLiODkpFhouELaZxwMkGInqhYhLvtIoupl8c2mVm+J4VlMfNGB/DVk1LZAP9F2fDH/2eFHEkRHABkJ0Cw3VKVlGw5jAnHdaRCXnxup1Ot+e9YhzQ/sWwVqOaE7WkhyT5iPoWQoyCl1bnStRJHPoTZpOX04bB5BZm2ybn6hQxpEyUkCrY2wj/zr5ViH+Mn4F/tA7Jbj2Ls7J9sqHtBRbaXl4RWFi7ABiIaQqtzk79yLej0JVUw0pdABl7d62Ozp7qoCsXsXgAVUo0YP2c4FnjBt7L6q6k3A9WcfwMtVdBtC0MvmCsijvgD0k/6S/frKkd7ouzMj+TI7YDnzJpDCnrsSVXv3dYuA2ajw0Qd+4WnDayEZemfDCBDpCIzWNIJGlIgR/MzVDANd7NP9ARs2S36dpjuZjZ9Lq2EDmKaofonpJ2J3pkHoG5ya234v9mOfXj1BygvYuLA3Ycwi2v2FEeBcLNWEqeFjMu6G2z6jv5bN+DP87hEhAIgkdjZ+WKQoD/q5u1a2R0wXbOmNahCdMzbkrjC3eNNiUN2fmmGBW27bGaq1y/Mm2z1dWQcPVWDIU0d2oP5QdbG7t7ZR9njZ6a8d/gf9ub2QCtnokn/qK8vW7EqFSAS+pa9oY0rMcjaQ6AhGFcu/k3pfriYnMm4J+F6mR
    runner-token: AgAGtHxdwCsmRGZ+x9WdUl4hMWwM0rwUl1DG8tOJkZRzt709Tk+4XdsNkZWSbszwnpDZRQp4OZ9aDZ1Xh4DwKQx/Ql0m4TE7QeZtCLVJrebQLM38Tk5lmieej1O5GWLZ4V5QKFnDjNcleHnuPaQzhsj6ep6LsK6198pp0Os9hFCmRah/7JzEPHlP14BA5Uu3mWFMECafawgoRe0kGfxMY8ViEgLE3aQ0mT/6WdoIl0nDFOv/SpBFglBL5msBhChaaNhbAraT//SQrF0CCIHu9UXZpT8wJ3O+P9Fx8C7Yzsu6hxiy3de1+XZf/a3mQifjBekODHUI7LTvE5ItArewh6c/eZxxZ3B9uIVtmnKjKJFl+paSVjpyyTayA7PMliSbMJe9w0F+rk0GTGKzCY/IHeIhHoKW1wdWHaQsHZk6kPmIa2aaSZ4746XiNbevJd6otcSUGlvnDcCp6vcRZW1pAAcZ9tybsoHir6WNRxFvj/Skg3CtsQyH6SzJ7RFe+grHPu7wtw37CUHkdL6p3ACXEM+ahrrBZDFxpkLINjwLq3Ww/6IzrQTOAfITIECbx3PPeaxZW9qk0k58EOEv82JlGgbrk3HggFDaEpf4NQWNhj7msQMRxwbdBDQaCiteFBXC+HnHxNiCiupKQDlQsnF5HdO3JN36ppKuU759SPIqKc5YDephilgmpelYRosrRtTrL1U=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner
      namespace: gitlab

