apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: gitlab
spec:
  encryptedData:
    secret: AgA+KWAWMEcHr0IFg1YkxhslThmuoCddExHlTRcLsPVhCTf27bi1giBtcE9KfSUOZlJFSsEJze6iEytIptBXlDg9SgPmOmK7hzaQs1n+Qe83/JrzuiTPtsAf2CgKA+ZsBmjgVomxF9DZMN2BSkYgxgwbkaySoD+Ei3pzZIF7Jn+IFrxuQq4RfAqKnLq+UxDCLeIAOekI4NnHeJvBp324M6Nx6TMCkjCNVURNhAUzJBIVeo7l3oIbPnBAAqYOghry7YMqAca6JgKhufHjdbxS/d6LuZlDN+VwxaEO/LvFJf+F5Kt0NZS6dEdkeS8svGF1sS0Sce6J6pTwz06/R9s+96nK9O/A1MhkTCluF+13ox82qocfm8EI7x0kkovzdixka2tHXdDpLvvG82g/grDrzqhsbE4/hDXhsOhVnWt17EYM90gM8p/PvKSF+9Ta7GkKhK704KE1+dsudigh/9fVn8DFYteoSF1CXyX3F+Lq7NHCOeJFQN6hBQPJUJJla86LpqP3i+ZNR8PgWWQevlPaK4Zoh2nzCfx1m2al/btoLba/N/Yp8fMivT9Hg3dG2iASIniju+9/HPcoCzYwuQgaI8MiKwJgy7APmoM5nf2deB/mrRtar7YNaf2+yh7c3qU789GjOSd+3I1LN0TWwRWMsGvrqLncH2+cF6PmpedAeNyeCWTU+QEzFA6LGUP9JH57085PnPWTWUJdgQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: gitlab

