apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
resources:
  - ../../base/gitlab-runner/
  - sealed.secret.runner-token.yaml
  - sealed.secret.s3access.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
