apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  values:
    gitlabUrl: https://gitlab.home.codemonkeys.site/
    runners:
      secret: gitlab-runner
