apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgAKRSjoOMAqzq+uHgIskuZAqhNp2yahViPcxU0apqBs22aTcLx2SkYG2EgautED46M6hUCocBYiCtVHGMuOIsT118ZxPswydVcygh0JKmwJTEZQFILnc3DsGiQqUa3ydgovGB+ur11RTRwQAmZiYLhIjpGQ4dNuUPg59UinDbs03GbrZHjfcPdfenJJiJgzAlvWII1B2IkzPSk4b/AvQL4e+tMjB65YujC3ciDkRbnlhh+zf4x1pOSAIfJc1ouicHtLUabRMWXOUKaeoBy7CMUxHk2EVyoexhY09gQNEmw7Sfu60n21RJtyOxRqRzQKkFH8E1IVuIqVYvGvD/aZAJ28zyqkOo37A3sMqtA603qw9UQji4dVpi6adc2T7/pR1Y8M2ruNDfwJFzDIs04AcuOpdCU1OY9WDvCWR2utoQJlwbm3JdawQeUyM2qmJ8LYgBsSGMOCcbl8yM87NLXdH/i+veEtXmLHGqYLCdyDReODu3um3EvPQXO5NdsySpvwr8G8HUQYwW5fy7Wu7Z//O2pi3jBYBR8+phP9NuRvnTpZUYPpE42ukNnzXuyCbzuMEi3CP8/xc3mRNrnpC24P8DaS6IMPFYqR3sobUxmFHv8UC4sQvdsvvrIaSUoqBs68LKZ/Apgid8UEAFangMtyirQIE/N6rQaBtL1lnwwYRUl8HQPeEEEOgjAARz8pUkDbJvIZbIp0fUl1IkoiPsdYRRgrgqQqJJU5ay/zr14/pgmFhjcYRAwA3iC7WeysOVwC3cgOpLsfF/dVU4R073WmGCGtDw==
    runner-token: AgBrTYgaA67M8oRj6WCodyUYQ0Nq44Zin2besl8zt9aUwimcNXs23ZJAPPeLIoJjZIphY+DephLp8BWVfdElaFD9JYQIwaYV5g3dopzvgl/yEhCGlvpKRm0TRD3H6Hh8qGCIPjxCCma2nOM5YOkLI6Lv146RGenF77ur1stynGDxJO5seoq1X680u1Jg+BFM2+4/0FLs3ngAYK/xZPx7+E+Ahc+WcUuHL3fksHfxc2JjWxliBn5JFC6EEFt2x0JhgLiVs2XzNlfhOqmiOCQJnuFWycDevEqedIGmrkwX6Jibo0PQ/+MNJ5tvuozY6XECjRn9C/xB6emUrdTnaTZxPovwOyPdyx2EQhhZK6fHUGVPTLeZ8uLgytKP+Rc3HkBz86mD79eeA86T9GoRRp61sepbAR26FVNJUgyta7HsIwW6oh3yZV/S/gv2FIYyYwByJw43KyGmayJv7XbxQIq3hXHd6sl25OIyx5DFF5Z4DbdquK+hK7wte+NJ/3zgTxqqT6YvUY9y6KTZ0OYFcJ0Y0LhTuMP0hjgsutTO2BYtkgSa+ivOmUWUk79HZ9pqoGoWznl9WqcschrUeFgx8Co/9bcSMJuLeaWmz0wtFLHRMiwKXiCY/r4iVhMpryZ91kORMjEDjEv9iYbx9IcgmlRvNDIyYVgQ2K+NO06Lb0EeaDKstF5FLfstri8gur5PNnm313Y=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner
      namespace: gitlab-runner

