apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgAZpid6Bh/xqc1GqImhGGsw09gggtZVE3FFy4jrmQ0JjLDkUN9t474rf0sJobZbvP+H6XLbNlMMHuLP12gHA1l1t109Pi8Y7yVorlEyRXRW8ON9erg3vB+UrEkKNQ7laEDX7N8JyDK5bkq06A/vWx/YnLgTZucB6Xf5eW5yvuFAywjsukjGmdxLZ/AszJN2wLfW5nuB6GGPFrKTmQzyL3xqY7njJ9n2D5XgluwAnc+p1A2qwE2lJDTVL96nzkMyx2XxMG5SafyL79QDoDKHahxItjZniGDBmdIiYtJE5vCHJW/7c1vy+2R4H4cfcbWtPqa81ZGh5PJoxj+InEkeYGOBpz2XvohiJvyCVRqQB5JVP65nTLB7O9nCxJ4cXc8/sVF1Hwoqmu0WNgkg/fmS0xLMDOBIuN46CTVdmfxEHsFHSoKITOEpUCvngDX1ORNxX9gy2fbeBatrle5MAF1+k/2xmsFLVjO1iwz3qVo6RQ6fy498hDZyidwgJv/Cu6sDPAZnanwvg0gul0OA/MMA3KdQJMbMkWhm9WD6p40TyRKcRuK71h7Ea6EkH+n0lnI1eqpf8ILPKuiJf9U5cII/N1ZwCmi5wLRAyKhzIL5r3gnUy2pqbd/nD5lo/enn6pqsEG4r4DqFXdMZrVZsE3yDcfxLi3HE4/JITJ33uLedGT6BBP85ZgImk6/Mkyy2vziiRlo=
    runner-token: AgAASUUgxR/gp9MvYSwtTEGFAL/qO68M4Lr6fLvjiDeDZJj7+vWLbqTBK9TSasqr4yLMGBZiS6c5xha/YdNuHC67+c5STdR5N+CZPA/OPUfN04vM7XCoSciVq5ChWbxI/CXeE0EXgre8j4xPcXSVipr2PqR05W7MCWuiOgOOZup9FyDANOojrpbN+ubMly1uM27z7ct0ojrnkEEL9iUItB+Mj9xSSB/QuCc8qrS/h0C5OgpxB7Xbrr07hcxoa/WzlTHSaSCM2ilU4WiNe1OQYuwMepx8cf1Ho6Z8Wl4Az2ckDNHJinErOo5G9bj7VAZcJYYf5aFYZ4oxHGitTs1qFJgD+vuZ0SZYp+lRHHxsSzfXzinYt8GtjVQ4S65URceukFSS5i67mIebaFG7v5CLj2jB7H1vXnTUoSPBBVySdgM2FS9g9MQuJ+/9RRIOKtMY9J+FHLK2WLvAk00XRPIO/Sn/m9+szGW7z7z4A0ilgb0glvI50OXhv1gKLREY8tfaRQQDwZuG4jlSoCG3ZIYiXvYOil+p0YYJSwcqpHV7oW7p7WGW/TSbW9z6y9vGRx9wib7S9JGvU88skpsSLMh3b48G58DtvAy+/50AxR0ruyDBtzfuM0WqHNbwhxHkK5w0Jyyv+FFkr55BDmbKjwk57LeEZw+3U5xaVJZdGTfSvWh+QqTYTjXp+loQzPC4SCVYIAvxPMUQak5G64RmQEwgW52TuqXSEKbwUllj
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner
      namespace: gitlab-runner
---
