---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgAq7nlnsuHLZuQV9O7CBrW165GSzJhAkzGqcnODhS8HJyw8u5YO2ucWYIvztHUSv9wSqO0JJwS6kZj39jNVheXeTv66KAcktVA2m+0oQxnRzlgRTexWqTIVYluCTxyKzVjV79tsfz3tHHfUi8BXbLmRRruLPVRhoPMtjodi0ICOmtsHn1iljUd18urLnIcsLiH2KLw8vUMolu4MBzOLXaujZA+QqaLBdMgxLCGrzVSppllU47YdVu90VIAJjjL4mWqrhi4hvMki0ltzw3NiaoKEe/HY1pewU89AnXTGbCpzZWEmfPvmJXs+y1InRrQ49QfPy8HSFzRvQRXEo4T+uC/FwxrmS3y2oFOjJNRQw2VU9rpoycs21PqJyJPZm3ehABZNP9DV/s5s8pRnJR093U6sk4ogQbec9KpbQ97RYbOoGqxtV0alGGysqIihreqIK9L22MOVeXVdGmq8adgbOUen4DhnIWVkkrDPILUM400dF2yqP9bXfwWpUIxJg4HFAsF3RUjXCqksGecHWlH+AIK925MQXb4EtD04tCLB7+mglVaX+A32OtQSMnws8fKLm2oAJbKyJtj+je6ds/e1Gvht5YyuBwK5fW1iOB8XSzQE+zdBFLfRKSbt0Xcq3a4mBurPkJcEjblad8g2cIWpYIFIzk3R3yIEjXYshNCx2jDHCf/HuE8dE3d5iIC5/pprv/w=
    runner-token: AgAYtJ12sVHpIDDCTnj7hSYnVDyi6CeUme5baZv5QZ0Zt7nqXAt0wIEiZxWEu02obD3A7lNMT+MWhGpWm6aedNi+mUU8Z4DCbIvatZMIwLxyKArzVQ4Mcv34Kif/7/5V16Ifw0HQCJ2USeM7dk1FeGGK2C8IZ1HT4A+O0ivVrbNIXVRgxAyKI144+3P+eSbepL1OT2bF8XKJ4bfIKv+Coss5kjPiLqMFb+7F+d1NK1iwJCTYR++6oDEM494t9t6+vi6Ib6l9AEnHUnkz9Z/JTj6yfQB9Jsf7LFRiiCtqOiY6j7zsJLEQU0DgtHx0yA83n3lSn8bLg58ZCmRf/PnAWclKDJrH/b4d/VjHhbdCdzrpK9t/3wM+iddU5TPmhwlR3gf3K7Te36d6O6klmxDFO/GInJOiINVAI0GaADEWILqgHZ4LP7QPsEGfT6s8Cb3M2ezwnBtkU4MDKzfqi98UkS3gjW6JHP+9MbD022GtFU2tGGgbQIHPe1kXTpvqjbjAdEGZOGUjvYY4Kla1GfE2cBGgxv1ZIRR4vlfjnqHpyb1vEbjo5+jbO5foVeruh3iWIf0lTr5zSprKQZxSg3oyimG6S25PsaUhEV8HxvezEueS3hcA/4vADjVI0G7mgXxqo5fN/pDntfckRqt6HPJoPDeS/gjiYcDr5yeg4SI9/Zk0TVvUR3gbnDwxvsko4PF1RJTFRrBsEDOhIzOvNhOVzO7/nvwFr1NoHpHW
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner
      namespace: gitlab-runner
