apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBTaf4zBjQrkJtqdWUpTgvWFaYMUfxOiJCXCR3lSWuINRQxyB3zPh0LPMvMJdD2YAMoOxfhHVP7bWGMht62mJml9vHLBGjLX31cAgIuXHNFbvr+at83rSnNkADF0o/hawm/sxWeqfOYRThOLCa8XOC0I+5pnKl2CO1qiWErsxF1BMLiwqxEzryDnb1d55IGCch5xpeXljoEQEM5mPOOaMMEiqKc9502JJoh7cns4ygfbIyQmcTsO8jeEY0uF+8sypXoKnEfudHHjTg4i2fD8aKVqI92QYzPnCzzd4LvNrrXIEtR2cfGNGJJis2BkhR5nTN3xawZKaZmCIxZD8LV19lLehc+gCNCjBcQJjmIoX5ClgLlCkVnEjWmKBbpSh5iwn29ws2kzbo+LCWzUgoUNxgmSHCoOxTMWYO0/iVdTvlZS9we6jqATw9kEyESP0HxqlsL4jqnT8hpOxRlE0FKkyTwT5dveKnEpZ6ZFpYPSAvQRupcQQS/507hrjk4XQtxnMJn/wUEmnBWHgCwfcUQicHsC819Bf4OUrnhEzdPysktoSpgfydGljZ734xOnQZ5GHWXxyNHvBJ0fBxLxoV4bsZPPJRuMi861unx4tJgPp73ivtMK0b439rS1yh4XTWZ35O/UJ0bFOau0KkTEEoFXh2vqGjfhHZSFny1iQyjnzYuTXXZPrN5bFV44/ZUAMYKqCHshQHn341QIA0GzW97+/nS
    admin-user: AgA3RumXjvyM/YpIlgMqrMuRAOsiahdu/rusSf+IQ2ctGxql2dpF3WugT/MKmTL+N5O/RJ/JAMkSVfrg9RCimV8hQELBy9qmMo92QGrotE7qR67OYB35WukjiEc2eRY/YTNrJtgxbDOQkXSjuNL7JU8PRSPzYdSTtpRqIo7dDCTqe92TNHJUbvy4KwtEez2JYtTV1biUioQAsh7OpYBdcM3R85uA4qu8eUHunGL6ZewKTK8FuHz8jHZ2gpilEmkDnRv9oTlLo716kfqVuLzNfRJBocMSJC9X+SB7VPlrjcS0gRiWlYfRyQm0kmDHraIYF4s1cjnW2UllEEdYkQJk6badKLuJEQRuhsXvX/ls+e0i6Mvm+8LbYann/j3z7e9MACOcAWEA3+9AaMgS+H1dOXPr9EOqxiFEBVbIwTVd/wpc3l78hAoGd3Yi6278XulbZD+TDa+ZF+dk2s8F7Y7JkNdBbxbtBRfWxpyKin7ChSaM2cAmoCH79QJPTYRk6hh3KsK/m0O6mTZ4SzkzuGm9EHMnvCFqZNuCcuEz6Nj/zsekMw8PQISQuzXJivolZhKOPKetwMzpAT97G4Zm4rZddvWoskZnnC3pVXQliW2NUh/HgkA6JR7Kf1MYqPANBSuhXefapjvHenf5dfyXa0bhwJsQyUOo9TeFMXEDfhg8yar8qK9oadg+TE2qB4oVYh0jcoMmSmEOnw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring

