apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: bitnami-redis
spec:
  encryptedData:
    redis-password: AgCKz7roh8Dy9I0cA1h58t3K/mZj3garqwWiWNCtxDkAPcDUifD2H11peYhtEszGMnrqsvIdAAlGAI5JHNWnoU52L+eorPcrMwTJzi3jNR+9J13CgaJC9WgKKTo0em0lHuQhwGc21i6W5n2wdMn5ZZJ3NLHVeoGRbzNLEB8mJ33MK+15LIdxf7r3pJhZBTA0OCCXlKlhDrg/IBgdnTassNKMiFzGRZnaXEcBBGzQkrZZQInsrLLwA+C5dz0W7IHHsTo3pIqFHKc5iSbv7y7Rx0JVSof/Hq20TOr0oN5CSns3TdBjYBjnMva7+ElhoMwtPFmtRN4bJ6v4w3qn6SUXDkwG4cyNUPEO3zX2dzauPfevLIwXeuQoRvf5N73tpwbCg1bFymGV+vaM8BxFmiD3l8e+duq9HVnNcuDqWyrefqx6PdIUlx36L5eSAoXAWQUCU3JtWwL94Qa6R2gOb2uH8Fr++ywYJA5xGJ5wYZ/obfzxOTSzCJPzJOzvSXNly7GRHqUuj64Z5trOnlJQEoX1pqItHjfaG0VNVgGErkYwcXKpP/9UXxNryiLQfe4fTxPLu64PkKZ6YSGK7amId/CO1lIK/IobUhDoCIqRRet3O8pj96HHK5AFPnhWieK6fcS+aAerJFtsC9qqn6WYnYnZWcX55PfGu3MLwLunuaSq64PT6Q67Sz9sj38lHWmbs6VFehBX270HgFPkow==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: bitnami-redis

