apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgBfbB58wMopN+ZHLf8OAQ2mGYqRpXdI/iBrGS0fW6NhHTnVlcKdY9pUkjc9UZRskFmzxixy8/m77AlNTelb98U4mDeFupQWIvK/PBcdwTtPQ2GT2fkikyWAk0aHtfjU3E7k3JsmvYZ7FOWEuT7ZBcyml9W8Id/6ugoxAJS12MMIb1R3p+c+EeAUDWMOv6olzuyGt+KeuyGH5i0/b8ZCbVLJpxR3LZXNlkYw9wFSA02LrLw1EvaglRPaknGafJIfUlvx2Y3Uh3WXIeBYKx/ks+YP0S/PxJ9MKzWygF1tJ9xG/gUa5htuw/LBcieC1dPNKGLrSoNMFGEPF6XVPGASMqvVyq/1l7rPxgon6NINENn2i+T3EiR5GeFwzcE3+UcD0rqLfJbrDif5JnpnACc50Dt5h0qnWJpY5TfMOQnQ93gVEQwyfYi9TbUa2vrq9YCdPpP1uVLoreMMyzj+kbL0lXo9VwkecpE0BtOi4NDU5STQU1c+w724Pnh9qkOPtY7ART4Xe66cBe07C2Kqx4UfPesV6ujlKY+N1n0FdUOW4oPFooglEN5asuIjmAfg4MfwoQyzLjPh6f7prY4H75m3yC1y3A8tYe2bylMNglYYCoZbOB35t3ODLLyNJM+NV+bscpk4SEmiJLoYEeumOC7JGN35y/eZHqoOOzOaovvM0bAW2aoKqPXxEY/+CVjP1hJwb9s=
    runner-token: AgB96dcvxOuO0SAJYgq8MM9lrTGfeEBgGBSBkP4yxqn2UPfVPOEMCQxsYf1nTUIFNUxoRw/kA5iMpYe2E17TjXetjy8twDfPQtz6N7OUD5kX4k7cNW4BylgSMY9L+ZdsRka/oK43c/zc8vVHfQ5o0AxvwNcuBJpFXHbJxSUInQ5mvQEzpztTRU+R6QPpm9eSmjCjwZeE/WeRPx3TtaxPVz0mSlWyRXlmI6brV3jt7/JGunYQxo+yOJe1c3FvlfPr/HVExCfeL7VfQu996OdnHLl43KWhefjluFKKkhK2CyhIDZufGncVEqelobATlTxGc45TLfv1zJzlbO8JDM0K+Aa2SjuFv2vvReOG+jAOG2x9deE2T41OaJ6sGNEE287e4UAq2vAxDPlDnUXe2EdLAEkpijbuP6KVJRY0/GsIdjuz2ie9UsTm5yxFECP2+xidmzPMBHCqRKOw7tShCkqpphlRb82C1vmuWZJPyUPTAww1pLDaBSdAFjZ9frvi5RdekT9Ua+lvxkRmsnoa7WjScWrib3vLCqArSpYIM775AzU47/+jCRvuzNXtXATHEO3L7BSjKprY1BOwUZCKBRbt6m84YLMNVc0ZCmSe4vP5c8pFghRdtnQQVGehLAuFtWP61xHMdd8zNxz0DDwlpQRv8+IVYapEcpRYW2PtsKVDouC4rcdYJ5autJoj8q5Ox6VpzRWNsGmghCpnKdHLONoYVLgM0PE1NQ/YEYhw
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner
      namespace: gitlab-runner
---
