apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-vanilla
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: ingress-nginx
  interval: 2h
  chart:
    spec:
      # https://github.com/minio/minio/blob/master/helm/minio/Chart.yaml
      version: "5.x"
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio-vanilla
        namespace: minio-vanilla
      interval: 2h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
