apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: bitnami-nginx
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: ingress-nginx
  interval: 2h
  chart:
    spec:
      chart: nginx
      # https://artifacthub.io/packages/helm/bitnami/nginx
      version: "15.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami-nginx
        namespace: bitnami-nginx
      interval: 2h
