apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 2h
  chart:
    spec:
      chart: mariadb-operator
      # https://artifacthub.io/packages/helm/mariadb-operator/mariadb-operator
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: mariadb-operator
      interval: 2h
  values:
    ha:
      enabled: true
      replicas: 2
    webhook:
      ha:
        enabled: false
      cert:
        certManager:
          enabled: true
