---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 1h0m0s
  url: https://helm.mariadb.com/mariadb-operator
