apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: podinfo.staging.pekware.club
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
       - secretName: star.staging.pekware.club
         hosts:
           - podinfo.staging.pekware.club
