apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/csi-driver-nfs/
  - storageclass-retain.yaml
  - storageclass-delete.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
