apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-delete
provisioner: nfs.csi.k8s.io
parameters:
  server: data.angryllama.net
  share: /mnt/pool/volumes/development/
  subdir: ${pvc.metadata.namespace}/${pvc.metadata.name}/
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
