apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: drone-runner
    namespace: drone-runner
spec:
    interval: 5m0s
    chart:
        spec:
            chart: drone-runner-kube
            sourceRef:
                kind: HelmRepository
                name: drone
                namespace: flux-system
            interval: 5m0s
    values:
        replicaCount: 1
        rbac:
            buildNamespaces:
                - drone-runner
