---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pre-defined-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgAYEsnOt2hDhdR/2aNtApW9N4J+0dYH3DfE18pZ/5Oxq7ItvAxagaTMVa7G8Seq5+hIaX9beSinw3DQEYm2/Ww5URQFA7Zj9bWcFitoog4084i4kWUhhbeyqFjPWrxxti8ebfco9Yo8vwzMUrA98v1rGtVlwSl3C58owDDFoktb4lS2jj0H6cgQAxsBJKCBraf5s5MQoO+UiyCl0bnaeNKrmciU0I3pkRemCl8gC4RJSDz195Yj3rtykcSydb97rlSONWtx6nQJRvDilY5Kd8BYwiM17iU8DG1lmSpulxld8FXNp33Fiaabs62zO38s2X6DkQ4DNOl8qdzIs+aG2lrwO414uQIKsBYqbkRftIZa2M8DA8CGx7SEYTxOfYP2RmAH8fap07226rZX2j0GTNRTLxYmu6PSFCW9liveh1Mc7RUEwBACoG3dKVCdNTh/X/DXPFrXNy5TYQLHQs3BnVypWZ4pKD5DobbAYOIrLrqJDebfE6avv7y6AhNcK4AI6eNPNBl/kGhM6EHhxWlfovGwZ9vH3sAz3MivXJv9PNd2KbpqckZZDFm+nlIwxnYev4J7yDUAc8XS8qwtSY7sXbjPGxOJ3nHyrCzXX1fPMjnOde1P8W8QMhtPkMoI8Z6PNMBWBbMZO6ZeACxAaw4pjsexO4dKATSVSByjoUakyAKTxrjVKnlc5uRXU7N6wqcs4KaiJzfu2nfwT/BIajTaYryDv6WMC21rJe9d0CN9KUqwGLXjgwXyev27
  template:
    metadata:
      creationTimestamp: null
      name: pre-defined-secret
      namespace: arc-runners
