apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-dns/
  - ingress-nginx/
  - cert-manager/
  - kube-prometheus-stack/
  - syncserver/
  - minio-operator/
  #- gitlab/
  #- bitnami-postgresql/
  #- bitnami-redis/
  - gitlab-runner/
  - metallb/
  - csi-driver-nfs/
