apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitea
  namespace: gitea
resources:
  - ../../base/gitea/
  - sealed-secret.star-pekware-club.yaml
patchesStrategicMerge:
  - release.yaml
