apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-delete
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-u20.pekware.xyz
  share: /volumes/k8s-home/
  subdir: ${pvc.metadata.namespace}/${pvc.metadata.name}/
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
