apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  values:
    domainFilters:
    - pekware.club

    provider: digitalocean

    env:
    - name: DO_TOKEN
      valueFrom:
        secretKeyRef:
          name: do-token
          key: do-token

    logLevel: info
    logFormat: text

    sources:
    - service

    registry: txt
    txtOwnerId: "flux-home"
