apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: do-token
  namespace: external-dns
spec:
  encryptedData:
    do-token: AgA2sVG3TPilJavJ8Id0CBjOvWzdFLb4GZ5Bunb4fHGD1q/2VWitRp3q2PRIx6Fu9W1xd2CFZ4FPcqb+GzARFFwSePfEfG+bula9atLeW54pS1sUotHyZNagqtmHZVmud5+obllkMi/2xExqONPlRSQOGRhCk15qoLBy2hNnxfzfyttCP1VWXj+rI6wAxOUISAoutBPBQ7e/D+3Gyer5hbro3hvKLBNDhNoQwygcGNkw/ZIX6HypzXum+NoxPQtr+2z61Slb0bLrcws3XrdsZrB5JJ0YbCEs/WLpeucM7whOa12D06rE3Dz190GqwOfsDYjecfFXDALn2j1FuvqcHYKnAXzUUCRY1cQrkP0EBkAKdCdhZtki5oby8pyY5q4G1XYoEJwMud9pnsz7yC5Wy/0GSHCT+OPFbI071bTSSJJU2IFP6/wDXfGL42Hkm3CJ3gDLLfnppgi7riI97yl/9YEw0zHILRSDroZQ+7/XVc9uqYnfWkzP8CUAdBvLBulQOVUDXxlF9ez6gyXHCKSlgVtLKyS88biNza1w7e/gtnUztqfeYjHqIOhwtwNDPPIKRe+yTjFVIGrkD0O3tH4nxj55cs3vY6wsFjbqpTik85du3zLP/x58rLjm1RmeYZ2lpP9mDjkkhJJ7+nft9ayEclGiPl8Pc0HeST74OtY0rcbpyxL8R0EDFqA4ZaaBmZuqGnd889NS+nbtNjXLLSYmaZJi382rcHBDff8d00V7QY8Sq3xKtBL5vOT5bM7lcTxDJkGoJy7EBwU3Ljpb/WnaYBYhUM0R4jYXAA==
  template:
    metadata:
      creationTimestamp: null
      name: do-token
      namespace: external-dns

