apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flux-webhook-receiver-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCFzJE9e0YcChIxvtNqXyH+Lzk/P6atiO9b9l7bC2MIQc81hPJQvYssTbS0Wbtp6uitU7IOB8hfCJf9WaYXKnfpQ7LfmODslN9uzEy39vBrFERKeDfOcV32+NEQYWlDKGcx0F4iGCXTp3aL6mWkEZGOffJyVFW8JDpxZHLD0fyC3pKbRW8RbcKjvzmpOcVaJ1ugcAAx4KbmkqR0bcBwOw+Pc1tJFHb2XyxHYjIe7D1/vJuLvUPEkQE5EFTnPbqvUUoiYzeyQgpQW/QIz5YNgRexCO5K5k4JNhg2kYDiEgg412BPQVwyo6vhslN/C87ZbCnAoNgCT3tKW7UJmXM+kGESo7cZfVZvUf4t5WTFQDDoC/n4/q5mDtunx4cjYUlnP9jquBH1b/gA9S447Ut5cd95M5l1O1rMO0j8tw9Ql8pt5gRl7DSX73pkGS9v2ybJVyOkzdo8sU1YaZ2DXgzZRZqqAHysUErb5ghlBAuPmq86CLxCUuiMRm5v3bpr+4oZn3MmDPqiwlzWylCn21iNRa9SriVJBNu2l0K8fg1YrsbQOPR54JhvUc9vWEsQFG2BP7shd/qlqNj18McjKrXjr/mXRHEtQFk4uhuxULNKj22astKqJfLsphOT9Z0ABoD4JPEtbJZHByM9VB0QRIppYmkeyQ6loEFqgxDAd1TUe46JpxMMzAp4vj9Z2aXzoHUb6JKe8xv3qSD2VFt7HoqPmPWOHkoJcOojq69P5xkb1oK/5xLrjgboYZcO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: flux-webhook-receiver-token
      namespace: flux-system

