apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-prod.star.pekware.club
  namespace: cert-manager
spec:
  secretName: acme-prod.star.pekware.club
  issuerRef:
    name: letsencrypt-pekware
    kind: ClusterIssuer
  commonName: 'pekware.club'
  dnsNames:
  - "pekware.club"
  - "*.pekware.club"
  - "*.development.pekware.club"
  - "*.staging.pekware.club"
