apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
resources:
  - sealed.secret.do-token.yaml
  - clusterissuer.codemonkeys.site.yaml
  - certificate.codemonkeys.site.yaml

