apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-dns
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgAWHPUcCA5nP1lXYY1IL2ckehmEd2kuc4uWRBMuJCerOmqt5FP0eqL4CGB8lCIWy31YH/+2AWknGjHkSj3N8W0LfVhzADxRg//2C3Huz1g3v0ckrszvjTfc+UR5XgHq4Mf5AGRpMwEG6T33OD7RsPtSLVCUQClhqnz4vfr50pthrBOLTed/sLWiuDOfFaZB8yaY7+5QCCaYSV5daGkUfVIW6rfVIfVK9UAEOrOddvbzdgPoLidlRmWpgNdDuoXq6VoW/aSmxVbCgedeGkG6GZKUf8jKa+9bZEYE2tL2HPCNKOIe5vDEIH7Yqi7VXxqiPHbzSEnEiI9aphT1cKRaeC/t+Gzdx4j/a0/rdaometTvh68gl89iB/1b+gXQREhd20A2/DKWOovA8OwiW7Ps5bE5dkkFLltSgbtEPePrgHxpBB16UjkgvYXrPd2Xa7PyCRx/GCICXvLNmel2VDoQgC5o9FGdhT7LAL/VxW1E1KAnmgbohVgTPSasOdsHdahyhyT/m3kFx7Nrac7DJluJBh1MFnmVS7g8IRD8/lLPZfv6yWYsqNqdnRnhKGg1Jr2HuBeeK1daVa/thBQnEwWbH/Iu54i8gyAD94zAfJpzCfsz+OhPxiQlAA2vk+5O7bCGuophUGt1qwoIlH6v1NZOTuFu1/RsiK9ZdMlKpNc3SlWTBUEb0MY+MLPJWy/V7ko9t9bhyUEr8GrdsWExKzBWuFavHIMeR2WKyNvwbeVYuJPI4RVQkvy5GIF4YxsKFX5wjtn8TkLPZYTF1iJm9YDKWN2jpPkZb6n+/g==
  template:
    metadata:
      creationTimestamp: null
      name: digitalocean-dns
      namespace: cert-manager

