apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: gitea
spec:
  storageClassName: nfs-client-persist
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
