apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  chart:
    spec:
      # https://gitea.com/gitea/helm-chart/tags
      version: 9.0.x
  values:
    strategy:
      type: Recreate
    image:
      # https://github.com/go-gitea/gitea/releases
      tag: 1.21.10
    clusterDomain: gitea.development.pekware.club
    ingress:
      enabled: true
      hosts:
        - host: gitea.development.pekware.club
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: star.development.pekware.club
          hosts:
            - gitea.development.pekware.club
    persistence:
      enabled: true
      create: false
      claimName: gitea
    gitea:
      admin:
        username: demo72
        password: demo72
      config:
        database:
          DB_TYPE: sqlite3
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        webhook:
          ALLOWED_HOST_LIST: '*'
        RUN_MODE: dev
        APP_NAME: "Gitea (development): Git with a cup of tea"
        server:
          SSH_PORT: 222
          ROOT_URL: https://gitea.development.pekware.club
          PROTOCOL: http
          DOMAIN: gitea.development.pekware.club
        actions:
          enabled: true
        repository:
          enable_push_create_org: true
    mysql:
      enabled: false

    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
