---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBUh2q9R0lZdn6mOJMmfwEjpo+KM+1XRIOrtDEwGpRuxVLjmaRDFKOBnqOP7SIEiKNPtZxBhU+jxKUuH/0vPFZSNOdBDNXAnMtuUTiU7oka3uXibkP1rUsXYge7uHlzF6NfqpeRz6W8hSsfkCE02/SO63MsK4I8x6nAC2y4sJ6RjRh2tpcFpFxpdz5LfRJQuCkHnvzOgE2NUC4gH2KZ3QcpEthxcUGLnrghBHUFKyAH10BAPG1gNMqj8zrJPxyikjhv/PK1+IeHMhpZO60BT3UF4EGJXTzS5NtQ2WUJa0Gezuxq1/1iU6Kio1IAQ3WbHXC1EUrzi70ONAFKxzfQr3a1uoZGC3vDcZxG5xiyPDMGo/ulAPo1LdvPxzZBOkPZxRfqTS8oA8CmOLD+1iSBIbHql6Z4kpw0GEWAA4qG1NGOtN+7OMg3uM6XfqNLA4ihhr1PeYkm0HvAPvpssTxmIc50Y+Lx53vxIt8z8k0k4UYM6/kiTs8NbB0aI/nq3L8CRaPWjkEY9SozoKL1p3Jqndmx+oq3kBs1TaCpXh1Kq9VP17XWJRMCxh95nLwNg/hCZGKz+U4jUejqYBP4hf/mWhWzFVpx99GydFblOajYeulBm/05rEcS8B3PaO5qaHqUk6YoRGYSJWfx6cWT3NzgckQBBEoyPYpwEVfM+7iu8YOgVsA0ywWwAnIofJ9S560UpoMVSU4Fakik6g==
    username: AgAnMZxWp8NEJzZXlr6Es/xfHQ6Vbz+9H3TDGpKVixl4s2uI/ne6jOSPhkhXxrw02Vd+BmhpkKevkJpd/DxcN/LeGXy29QinKMllYpLfhofV8zPQpnFl1cscnFHYWJQtixhCZ2mACY4l0/tFrBA7nqjNiuXHoizLZEL1ISGNzjwYlYj9tk7gmLqmiMKAEObf4XDb7kPO3GysonOJwe+K3tGbYeCNhzEermSZlsPtBlxDukzACHzRglwNchNthKB68g1R4rgfoEtgcJ5Ka7bQryLa36QhWDJRpzmR7cRTauXVyMEaMvaKUZ5Q9ybLhOcG1ks2SeI2TXpbJ6Lg5jIXAllQKqd0wInN4XOZ9zVU4yHG6SYzK102aRVwe9HcXSv1bc1Vh7v0E6UZKVgPKhwicibFWejvjMiR4Ijs8Ujyfrn6UGnXUHO4fFalaYT1SFkUQeH7qZVIfEsltP5IdFGDTr0U4D2yxCavB7ZplQ13F8g7koo0JNqIc4u2rt4A8JijgNM2sgJg8MvyUONNbXpdExQC95Brjnv5Xlcj/uDKYoeoP6yEOBnFF6n2vgrhNLvVn0y79V2VS/hSKQQf8ZYlq6KW2Q0TVf4Yp8CzvVGO8WC3rNrWxcoqB8g293V3i2hW3qWW5yeYgR1KCYlnQ6dZFrzf7goPcqVER9BY1hDnP7Qxo5FdM1Qov3oauMTw/VYgDDA6tlzSV28=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
