apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: bitnami-postgresql
spec:
  interval: 2h
  chart:
    spec:
      chart: postgresql
      # https://artifacthub.io/packages/helm/bitnami/postgresql
      version: "12.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami-postgresql
        namespace: bitnami-postgresql
      interval: 2h
