apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBcMitIGixj0lup3j4K3GT9+KZD8fsobYQ7jatZGZqn9f1MJ4NF/VkaMDQSIV0JFaXOYAzBqMP9JXfUml+9/qCrETkIW7kyyZsK8IABto3GvegUIOEkmUXa83CwLX+ShjD4vLgdyI9sMifkMmbs46+SiiFeO6WTkk1L1mQln6OAZFdIL5jpdGZBJMvugmUA1JoE/cdJ5O41gb6loYtNHLYKmVDQfxudYuPhZ7lykV5PoP7OdG6XXPL9QkfNrtotTm1cu19xJOobDIps2KJ5GNyFz4G1za3/TLaCIHICow+/JlchCz/wXEYgrgEHWnqZ/tUqHvgfjtD9YqudCKFLqakTMVvuL2Myr96IUvxvEqRxlE6GJb86SbmcBXpictvYZEG4lcMB/nSCdljzesv7AWQLAFWcj8r/Merqc9RsQ09HZJZGw7PybaHLIIoHFXX817TADW7h2Cyo47TTZyq7RBNS4KxBMBaKVUD4ev9UN15gknd8yTvpngpRY84gomIwdLLI6UZpSAF+ltmNKBdYE02628R8Ot+TMuW7hTXGmt1s2hEoIHnqahWf2+1EAbfl4rib4qyLdDF8a5krfZUCgNNh3dHID+AslGrPg6VD2YDOvdLwgsEdYQEuUjxsgHBBlatgD6ycOWXd1/S0tVRqJVgZjPC4hhMQwjE/JPlUoYgMpmO9Mv+Nnt9PF6FZsCrURHCDICUfluIPSYQawuUEcXQ=
    username: AgAFeHMBCBU5o+czflu15jpkXSd3qMamue5AIlFtZv3gb8qvR1ZRjJQAH3rPYqh20eZ1C1aY/C3ZcjbWiv3mXtrCDg4BxkEjZ3tUUJxTSzZala+vgQQart6+VbrPa7t9q5s8Ye5M1O7ljay9RKuhus9+4mXFeGjeBzSs5rb3gZ6R2GjkBeX2QZJozM05JrE6JmQZSnkVQBw0sjcF7bMHpcpRXaaOmAiifDJHybeaFiJhLyaPleNinZNICHe99GwMpZh9dK4hbt/lgwWKyG7WR4c18gyBGGxpLlr+Tx/+0WDYaIwb/g2Ex0fBGS2lOBhXLmPp+D87OFk4FdgeznGgJWneQo5CsnXDo+Td1FNp9uQ6YnNTHfmUaE3yX9UxOt6uH5aPSyOJMN7qdksM4+AyZD/V7uRTqYBQEQ9+etwEiPPl9Y0hsI0Toa+DLfu6z5TM2MH2FMXgcrN2EpRLgxXjiR8+ei2vbo32+RF0A9pdqq5oKJNGuZ4JgYLc8Gjm5vrJk8jpLtCSsjs+4y2yt1/nv+bZZ6ViQXiC/RAssM+Ykkbouejx3Yy4TAv1CJGMypBgDY0O/1TFmgR7AZplZHpW45VxPFYhYqDNh23CzJjx5kT17PuFG8Y8eH8O5VPB6jjEea+XBXYdaBh8Fg3agxliFYzVIqYS6VzsZ4ECMNVQPBpB7UbHV4LtNCnsvi621UrcspvTLn+QT1vOivA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque

