apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitea
  namespace: gitea
resources:
  - gitea-admin-secret.sealed.yaml
  - ../../base/gitea
patchesStrategicMerge:
  - values.yaml
