apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: gitea
spec:
  storageClassName: nfs-client
  volumeName: gitea-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
