apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBkxc8HiL1znH/j2xfFwCMIPmOLgDqjJNnTwOjeHfaIfeJcKZIZPNuF8LZFGx3XypuOLZAfNZxh9NPPyXkNFK+7hjroCOe8IEtWWbP6kITZaQ+tN1ex6GLNpw1dOHhHI2VEY29dw+8cTR5QRdfX3lBUwVxvLrotlKpl0Msgp4r/8YYiS24AGUI006lGk3RuG+6Gy+59hBwCd5GH6MPJYijfWhndB+52IgrcAp8XRQGzWZ6fExIQumS9IetpZcF+GJ0AzN8IWGLidoZRq3q9tlt72aLb8CN02trAg0WNXy3/ASrOv1fjI67fJ6+EoDk6JjaLpf69I4SsCNe/HaYd+OvCLaQTPuguIJs4DOxhDjOqKv2QOSgRjSFZrZjlSKQ6k1HBoZCP8MLbN0KC+nqoIdzeVJfpL4Jcg9B2tebcWevw6gITJa6Jld+oTtvnPMtESXgvnfqNbC97hWuE9weOzjWKFO5HPFLAdlNARxze/pYbAkUnZMocN+xBOrti2uI/YwJKI5VO7duCFo4EW9P3kkxOTxXmoMVOzhQjWGNRXlCMbmFiGiiVlZimymYMDI5w96uCjFB4iVPjA+zs1YUOk6PlMSZrYK86xQYj780/CuiY+fIWOSMUPDQA6RTwi1IGQQ/U4UelT0zf05D65fi1IYiTIi6pemj5aQJJIlJQ3C6p1oHwPQQ1qRea46v8C7mjLgX+Eip3dXDos9e9OdwmYNE=
    username: AgBtBC/tgV4WMlzq4FsgdWve7GhL9RQxmx1qlUd3KHr0TKQ1LBX7yKEzhY1yrIYK/ePKWmL30A3891i++DglIuLkGowwTEacud3SOYSgkWSdApq0s+MKDrw27iOHNlmzO6dqtq+f8kfF2W5oE/C6vgimXEjtgXN5ElD4k1HltLKPkaO5YxREjT1UPOyHE7Hr97ME3EXtF6TagL91l2UKsU7JJEnvo96WEAZX6FARF6nHnzS7b6cBGBsvsouUB2Z85nENRiGgDFFHuXdKLieYsvU01XeOm0p5nYQjf/vD/ieK00mrDGB6FGo1bendT1eSxUGbB2WPJWE9DmfoQLV+7EDR12qeuP8aSWEHBL8XaJD46S8tR63DZjpd7HxDyaBhhiz8NcHOiCr7tONivRLsq0OQ+4gyw+NrXxPzadCjMpaumnCsWxgCaUJgDN1gIyv61xdUaeSblQCP+nExEXAoX2WCipoJekVQK6TJu1lL6w4liB7R6LlhGWYvTXosFj5RDQ11SuBTxKJVmt/xO0ndOPRrwGwfqH5RzmJXxjoxqdpzx+d6AlEhNYpWTsy42MYfGzH+KEvw1GUVEUaviedc1B+x1/G+dgay4GR3fsykMMKge44lc1W6HT+vSF/UoPoTHPquPxtRX5aStLf25Rvx6KlE8NMq3zFt6GmgM3MskDlYA4wlU6zKGYdCRAUAXP0pOMis/zHpABCcQj8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque

