---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
spec:
  values:
    nfs:
      path: /volumes/k3s-colo-single/
      server: k8s-colo-support
