---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-sep
spec:
  values:
    nfs:
      path: /mnt/pool/volumes/staging/
      server: data
