apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: ingress-nginx
  values:
    # https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/service.yaml
    grafana:
      defaultDashboardsTimezone: cdt
      ingress:
        enabled: true
        hosts:
          - kps-grafana.staging.pekware.club
        path: /
        tls:
          - secretName: star.staging.pekware.club
            hosts:
              - kps-grafana.staging.pekware.club
