apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitlab
  namespace: gitlab
resources:
  - sealed-secret.star.pekware.club.yaml
  - ../../base/gitlab/
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
