apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  values:
    global:
      edition: ce
      hosts:
        domain: pekware.club
      ingress:
        configureCertmanager: false
        provider: nginx
        class: nginx
        enabled: true
        tls:
          enabled: true
          secretName: star.pekware.club

    certmanager-issuer:
      install: false

    nginx-ingress:
      enabled: false

    gitlab-runner:
      install: true

    gitlab:
      gitaly:
        persistence:
          storageClass: nfs-client-persist
          size: 50Gi
    postgresql:
      persistence:
        storageClass: nfs-client-persist
        size: 8Gi
    minio:
      persistence:
        storageClass: nfs-client-persist
        size: 10Gi
    redis:
      master:
        persistence:
          storageClass: nfs-client-persist
          size: 5Gi
