apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: ingress-nginx
  interval: 2h
  chart:
    spec:
      # https://artifacthub.io/packages/olm/community-operators/minio-operator
      version: "5.x"
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
      interval: 2h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
