apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: bitnami-redis
spec:
  dependsOn:
  - name: ingress-nginx
    namespace: ingress-nginx
  interval: 2h
  chart:
    spec:
      chart: redis
      # https://artifacthub.io/packages/helm/bitnami/redis
      version: "17.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami-redis
        namespace: bitnami-redis
      interval: 2h
