apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-vanilla
spec:
  values:
    mode: standalone
    existingSecret: root-user
    persistence:
      storageClass: nfs-csi-retain
      size: 50Gi

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 512m
      hosts:
        - minio.home.pekware.club
      tls:
        - hosts:
            - minio.home.pekware.club

    consoleIngress:
      enabled: true
      hosts:
        - minio-console.home.pekware.club
      tls:
        - hosts:
            - minio-console.home.pekware.club

    resources:
      requests:
        memory: 1Gi

    buckets:
      - name: velero

      ## all the "bucket" references in: https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/values.yaml
      - name: git-lfs
      - name: gitlab-artifacts
      - name: gitlab-uploads
      - name: gitlab-packages
      - name: gitlab-mr-diffs
      - name: gitlab-terraform-state
      - name: gitlab-ci-secure-files
      - name: gitlab-dependency-proxy
      - name: gitlab-backups
      - name: registry
      - name: gitlab-pages
      ## deviation from chart source; to differentiate with non-gitlab runners
      - name: gitlab-runner-cache
