---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: root-user
  namespace: minio-vanilla
spec:
  encryptedData:
    rootPassword: AgBj/mKq3PAFgj15Pozn+vHGoGj4hxX+pkQlTsNP7jRQ5qAwfizLdASlFHpbG9N9CePnErZ7/9f+LtRUHqVPIVQz6RBSvEb7KLWPwryN8edj5R54hsWnVU3F4iLvS9mLyPlZ8Dgd32Rvx5mB+2emHWJiLD5QdKhCB3SCBEv6vC8diFONcpHK+W1g22PamtqTc6hCYv2fiOGUN4WpMqwwjqjAOQinIbTM1+WCYZQYJVgKpQrFQIv1JgJGNMiQpVUGkPWnclQ/vZm+c39UD1a9gYJ6HB3mwNFyQo8qsacIhS/YPhlZc8wJpY1BVbQaV0fSs/SwX2x/bX7NDM+5ovtGV2gQ6Uc5yD68HdgGOu6J3No956P0RAPA3EcKhctErnBsTh36H6VfoqT4Vv2COZ61sHzSsHqbXNtSpZR2jHKdQurdzsG762MMPjYrJEglxoB105/cN5yWcA1XKf5Y9CCALYFFbmxzpM62ZKyDw2Gkt+wwHiBkhaauikfUUHnlW0Q0fcidpFC88qlT/el9Hah/3YHXamInmKXD12vEP4eDtWG4qT480gM2OquO18gbLukLzsPAc45gdGlntV+Iz1B59GJQklMCDLpn7kkVR+9cUbVgfSQTOpspMvjPiSHzC4OP19Z9/0YilfwBPUCbRkqdcZH1bMbdsk92YwAODu8Ga7lM1Zp5tbSthCkr6ZEHuTgwNhABlIW9j+TCvA==
    rootUser: AgBw7P1LUqgbNpoJBgf/viXieb73L65d0W0MHmKeQJmRzh0l0tZtTAsTkZuyRyoVPB8vz6qBJSrdVHwYwt9eBJGFIJmS8UZTlGJG70T+VohrlLS91kZLEyyRfdh/sKASEjKj32tKEf7unaB775P+u8KCz/DxzD3s5iiLGNzLWw1TdYCa9iAfYA8RYNbZUwO5IHXnfuU3cOjlMXCbxhcHbzdkVI4W5OEADzm0Ntp4nDIMGQlrHsgb1ICo5QqFdTYC+tlaGnbHV22uzKYKbeuVC51vUq9RMdLJoFrgajP/TyU2z+JSMDqxiot3No292srlQ0bp9DbSNbVwqSHAQR+TKs6l/pApr41+bTeXeaBt3DEPKYlyPiINr6LtTQ9OElz0L+4LT18zsCNvKWHL9mYj/u+/3IGWnmx5DC0DqOJFY7p9W6FfE7dvbqnBfeyhTHxe58KBJ8QvZxEefowVZJxHiM5j5jS6wH8forf7CejN1m9rVJJQePK+zsgXcYOgZNisJrb/B0raGUy5kbC5h4U/iy8pLNKjec6cgod4yzzmBat2yr+Pf/M7vpIjbzpVCkPGFOkxHYfL8f/j2sw+PImo5Nw9sxCm6/qW3GYKut7JqWkSsmmR+obKt6WdqZFnnIfuUXG1g5Ex40viTAyPkoO5Z7xGTRbc2IEbDxiadl/iRlLChPEd1ET+B0g6Rz1n3qkg3s8GC5D+m82f
  template:
    metadata:
      creationTimestamp: null
      name: root-user
      namespace: minio-vanilla
    type: Opaque
