apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/bitnami-nginx/
  - sealed.secret.star.development.pekware.club.yaml
  - pvc.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
