apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: bitnami-nginx
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Mi
  storageClassName: nfs-csi-delete
