apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: drone-runner
    namespace: drone-runner
spec:
    interval: 5m0s
    chart:
        spec:
            chart: drone-runner-kube
            sourceRef:
                kind: HelmRepository
                name: drone
                namespace: flux-system
            interval: 5m0s
    values:
        replicaCount: 1
        rbac:
            buildNamespaces:
                - drone-runner
        env:
            DRONE_RPC_SECRET: ENC[AES256_GCM,data:bDhZjE4dmCSIopQIxZTyOZHjMKL1So9XpRIljxS43VE=,iv:tpPAGKi9a6XYJER8MsTt3C8yKxWp9pROzu6MoSxFZ9g=,tag:p5nmgR4liUMJi/AvSGlsDg==,type:str]
            DRONE_RPC_HOST: drone.pekware.club
            DRONE_RPC_PROTO: https
            DRONE_NAMESPACE_DEFAULT: drone-runner
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-05T23:50:04Z"
    mac: ENC[AES256_GCM,data:SvsYR0qaeVp5pnQYewERiJeEQ2aMAVF7BpctnBdEolNX2TdqKGG4pTHwnzC1FxS0ZMszjIZPykzOSgVQy4P5qkP7w0aytsLZsiJO2LqZ79SPYdyZcXK1CP9rMD6LfTbbHPtmzlPBFdb3hChGUz4vMG27bCk2xm9ROpzfoaj0ozE=,iv:zWpijazAUDU3GFAWB+sJO5ep0WXjPhxfO1/INlLSZG0=,tag:TJfZ3hoBkGzrerrHYQcDUg==,type:str]
    pgp:
        - created_at: "2022-07-05T23:50:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA39JIzDKQyQnARAAsvUW8SeHyh7FVGBODTaXP4vrd905BuRuvWEQW2J77Dwm
            6D/CEuqacdfbWQWfQvTGkZYUb9VX6l1gljwGbELmI0KFs1FzHKV57cjBz8A4MXuS
            hC6QDuK5gACckZyKgSqG5tbfPNYFM/gLeNAPZjBKaW0N8/u07g3DgWkDexVCPeds
            wpznuybqHPrmdWrq+jeVL47IG5fHkFcj5w7bVo8S/ts831c1NZikuR/WONS9g2uD
            g7s977MmJ/9JZAW5PI+in2YboPuePb347IEql8q2r5u5is++WhvUObbvAOjcF4yi
            ECRYxnaKgRnAVN9H4Q2URG4ZhkpCicuqZ9I70a+X/OyiiKN+oCZZ/aKuiIwjQNKh
            yMh2zb3Fx9+z9kfEX9Si9xMXvkT08eY9SxkOI6+5aEwJFwNIBJcN4v8hKOdaaFSc
            FCYk/mikfw2avUkhsdRQnlrCpAXeMR8TxuSnEa6n/fk6Jau2SwJ+f9M2kjkVUpsm
            mWKWTeqtzLjVLgCPBpMTi28bULjfITb7Af4eFU9U38sqQgunfgTNDsLIGtEkzcMB
            e2653PmirXIrAd9toNzMoWoYhYSAh0aP3yySpYix1x1iFGSfUYbCEKcnpeyXwVHF
            OcSETIRfmXgmBSYyXHWWqLaKrQ4taZnSZRWVDTySwDKX2JHP7c4ONZFq+Q34B3jS
            XgGA6tvgnUrh2wIshzNV61jDkAWWQcO/OX9jacj+ni/JAEgNauQQHqdqJkzLejSl
            t9PMSeDMhmWkVsD0HMhvyeDS5uSlLqwcVH6L8Ih9o0+w/qUuNPh4/AYe4WGwCGk=
            =SqyH
            -----END PGP MESSAGE-----
          fp: 2BBD3786044CFFE0260484332213C1FB5FFCB338
    encrypted_regex: ^DRONE_RPC_SECRET$
    version: 3.7.3
