apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
resources:
  - ../../base/ingress-nginx/
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
