apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: gitlab-runner
    namespace: gitlab-runner
spec:
    install:
        remediation:
            retries: 3
    interval: 2h
    chart:
        spec:
            chart: gitlab-runner
            # https://artifacthub.io/packages/helm/gitlab/gitlab-runner
            version: "0.x"
            sourceRef:
                kind: HelmRepository
                name: gitlab-runner
                namespace: gitlab-runner
            interval: 2h
